package com.itos.model.ext;
// Generated Sep 24, 2014 5:12:05 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberPaymentTypeHistory generated by hbm2java
 */
@Entity
@Table(name = "MemberPaymentTypeHistory", schema = "dbo", catalog = "rtacs"
)
public class MemberPaymentTypeHistoryView implements java.io.Serializable {

    private int rowId;
    private Date createdDate;
    private Integer paymentTypeCode;
    private Integer approved;
    private Integer changeCode;
    private String name;

    public MemberPaymentTypeHistoryView() {
    }

    /**
     * @return the rowId
     */
    @Id
    @Column(name = "rowId", unique = true, nullable = false)
    public int getRowId() {
        return this.rowId;
    }

    /**
     * @param rowId the rowId to set
     */
    public void setRowId(int rowId) {
        this.rowId = rowId;
    }

    @Column(name = "change_code")
    public Integer getChangeCode() {
        return this.changeCode;
    }

    public void setChangeCode(Integer changeCode) {
        this.changeCode = changeCode;
    }

    @Column(name = "payment_type_code")
    public Integer getPaymentTypeCode() {
        return this.paymentTypeCode;
    }

    public void setPaymentTypeCode(Integer paymentTypeCode) {
        this.paymentTypeCode = paymentTypeCode;
    }

    @Column(name = "approved")
    public Integer getApproved() {
        return this.approved;
    }

    public void setApproved(Integer approved) {
        this.approved = approved;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", length = 23)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * @return the userProfileNameTh
     */
    @Column(name = "name")
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

}
