package com.itos.model.ext;
// Generated Sep 24, 2014 4:56:36 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberDeptHistory generated by hbm2java
 */
@Entity
@Table(name = "MemberDeptHistory", schema = "dbo", catalog = "rtacs"
)
public class MemberDeptHistoryView implements java.io.Serializable {

    private int rowId;
    private Date createdDate;
    private Integer frMildeptId;
    private Integer mildeptId;
    private Integer approved;
    private Integer cancel;
    private String username;
    private String frMildeptName;
    private String mildeptName;
    
    

    public MemberDeptHistoryView() {
    }

    /**
     * @return the rowId
     */
    @Id
    @Column(name = "rowId", unique = true, nullable = false)
    public int getRowId() {
        return this.rowId;
    }

    /**
     * @param rowId the rowId to set
     */
    public void setRowId(int rowId) {
        this.rowId = rowId;
    }

    @Column(name = "fr_mildept_id")
    public Integer getFrMildeptId() {
        return this.frMildeptId;
    }

    public void setFrMildeptId(Integer frMildeptId) {
        this.frMildeptId = frMildeptId;
    }

    @Column(name = "mildept_id")
    public Integer getMildeptId() {
        return this.mildeptId;
    }

    public void setMildeptId(Integer mildeptId) {
        this.mildeptId = mildeptId;
    }

    @Column(name = "approved")
    public Integer getApproved() {
        return this.approved;
    }

    public void setApproved(Integer approved) {
        this.approved = approved;
    }

    @Column(name = "cancel")
    public Integer getCancel() {
        return this.cancel;
    }

    public void setCancel(Integer cancel) {
        this.cancel = cancel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", length = 23)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * @return the username
     */
    @Column(name = "username")
    public String getUsername() {
        return username;
    }

    /**
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * @return the frMildeptName
     */
    @Column(name = "fr_mildept_name")
    public String getFrMildeptName() {
        return frMildeptName;
    }

    /**
     * @param frMildeptName the frMildeptName to set
     */
    public void setFrMildeptName(String frMildeptName) {
        this.frMildeptName = frMildeptName;
    }

    /**
     * @return the mildeptName
     */
    @Column(name = "mildept_name")
    public String getMildeptName() {
        return mildeptName;
    }

    /**
     * @param mildeptName the mildeptName to set
     */
    public void setMildeptName(String mildeptName) {
        this.mildeptName = mildeptName;
    }


}
