package com.itos.model.ext;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.hibernate.annotations.Formula;

/**
 * Operation generated by hbm2java
 */
@Entity
@Table(name = "Operation", schema = "dbo", catalog = "rtacs"
)
public class OperationView implements java.io.Serializable {

    private int operationId;
    private Integer operationTypeCode;
    private String docCode;
    private Date docDate;
    private Date approvalDate;
    private BigDecimal amount;
    private String remark;
    private Date createDate;
    private String createBy;
    private Date cancelDate;
    private String cancelBy;
    private Character printedStatus;
    private Integer memberNo;

    public OperationView() {
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "operation_id", unique = true, nullable = false)
    public int getOperationId() {
        return this.operationId;
    }

    public void setOperationId(int operationId) {
        this.operationId = operationId;
    }

    @Column(name = "operation_type_code")
    public Integer getOperationTypeCode() {
        return this.operationTypeCode;
    }

    public void setOperationTypeCode(Integer operationTypeCode) {
        this.operationTypeCode = operationTypeCode;
    }

    @Column(name = "doc_code", length = 50)
    public String getDocCode() {
        return this.docCode;
    }

    public void setDocCode(String docCode) {
        this.docCode = docCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "doc_date", length = 23)
    public Date getDocDate() {
        return this.docDate;
    }

    public void setDocDate(Date docDate) {
        this.docDate = docDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "approval_date", length = 23)
    public Date getApprovalDate() {
        return this.approvalDate;
    }

    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }

    @Column(name = "amount", precision = 10, scale = 4)
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Column(name = "remark", length = 256)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "create_by", length = 50)
    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cancel_date", length = 23)
    public Date getCancelDate() {
        return this.cancelDate;
    }

    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    @Column(name = "cancel_by", length = 50)
    public String getCancelBy() {
        return this.cancelBy;
    }

    public void setCancelBy(String cancelBy) {
        this.cancelBy = cancelBy;
    }

    @Column(name = "printed_status", length = 1)
    public Character getPrintedStatus() {
        return this.printedStatus;
    }

    public void setPrintedStatus(Character printedStatus) {
        this.printedStatus = printedStatus;
    }

    /**
     * @return the memberNo
     */
    @Column(name = "memberNo")
    public Integer getMemberNo() {
        return memberNo;
    }

    /**
     * @param memberNo the memberNo to set
     */
    public void setMemberNo(Integer memberNo) {
        this.memberNo = memberNo;
    }

}
