package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Formula;

/**
 * BankAccountType generated by hbm2java
 */
@Entity
@Table(name = "BankAccountType", schema = "dbo", catalog = "rtacs"
)
public class BankAccountType implements java.io.Serializable {

    private int accTypeId;
    private Bank bank;
    private String accTypeName;
    private char status;
    private String createBy;
    private Date createDate;
    private String updateBy;
    private Date updateDate;
    private Set<Member> members = new HashSet<Member>(0);
    private Set<MilitaryDepartment> militaryDepartments = new HashSet<MilitaryDepartment>(0);
    private String bankCode;
    private String bankName;

    public BankAccountType() {
    }

    public BankAccountType(int accTypeId, String bankCode, String accTypeName, char status) {
        this.accTypeId = accTypeId;
        this.bankCode = bankCode;
        this.accTypeName = accTypeName;
        this.status = status;
    }

    public BankAccountType(int accTypeId, Bank bank, String accTypeName, char status) {
        this.accTypeId = accTypeId;
        this.bank = bank;
        this.accTypeName = accTypeName;
        this.status = status;
    }

    public BankAccountType(int accTypeId, Bank bank, String accTypeName, char status, String createBy, Date createDate, String updateBy, Date updateDate, Set members, Set militaryDepartments) {
        this.accTypeId = accTypeId;
        this.bank = bank;
        this.accTypeName = accTypeName;
        this.status = status;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.members = members;
        this.militaryDepartments = militaryDepartments;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "acc_type_id", unique = true, nullable = false)
    public int getAccTypeId() {
        return this.accTypeId;
    }

    public void setAccTypeId(int accTypeId) {
        this.accTypeId = accTypeId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bank_code", nullable = false)
    public Bank getBank() {
        return this.bank;
    }

    public void setBank(Bank bank) {
        this.bank = bank;
    }

    @Column(name = "acc_type_name", nullable = false, length = 50)
    public String getAccTypeName() {
        return this.accTypeName;
    }

    public void setAccTypeName(String accTypeName) {
        this.accTypeName = accTypeName;
    }

    @Column(name = "status", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "create_by", length = 50)
    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "update_by", length = 50)
    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", length = 23)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bankAccountType")
    public Set<Member> getMembers() {
        return this.members;
    }

    public void setMembers(Set<Member> members) {
        this.members = members;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bankAccountType")
    public Set<MilitaryDepartment> getMilitaryDepartments() {
        return this.militaryDepartments;
    }

    public void setMilitaryDepartments(Set<MilitaryDepartment> militaryDepartments) {
        this.militaryDepartments = militaryDepartments;
    }

    /**
     * @return the bankCode
     */
    @Formula("(SELECT bank_code)")
    public String getBankCode() {
        return bankCode;
    }

    /**
     * @param bankCode the bankCode to set
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * @return the bankName
     */
    @Formula("(SELECT B.bank_name FROM Bank B WHERE B.bank_code=bank_code)")
    public String getBankName() {
        return bankName;
    }

    /**
     * @param bankName the bankName to set
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

}
