package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name = "Bank", schema = "dbo", catalog = "rtacs"
)
public class Bank implements java.io.Serializable {

    private String bankCode;
    private String bankName;
    private Character status;
    private String createBy;
    private Date createDate;
    private String updateBy;
    private Date updateDate;
    private Set<Member> members = new HashSet<Member>(0);
    private Set<BankBranch> bankBranches = new HashSet<BankBranch>(0);
    private Set<MilitaryDepartment> militaryDepartments = new HashSet<MilitaryDepartment>(0);
    private Set<BankAccountType> bankAccountTypes = new HashSet<BankAccountType>(0);

    public Bank() {
    }

    public Bank(String bankCode, String bankName) {
        this.bankCode = bankCode;
        this.bankName = bankName;
    }

    public Bank(String bankCode, String bankName, Character status, String createBy, Date createDate, String updateBy, Date updateDate, Set<Member> members, Set<BankBranch> bankBranches, Set<MilitaryDepartment> militaryDepartments, Set<BankAccountType> bankAccountTypes) {
        this.bankCode = bankCode;
        this.bankName = bankName;
        this.status = status;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.members = members;
        this.bankBranches = bankBranches;
        this.militaryDepartments = militaryDepartments;
        this.bankAccountTypes = bankAccountTypes;
    }

    @Id
    @Column(name = "bank_code", unique = true, nullable = false, length = 5)
    public String getBankCode() {
        return this.bankCode;
    }

    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    @Column(name = "bank_name", nullable = false, length = 256)
    public String getBankName() {
        return this.bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    @Column(name = "status", length = 1)
    public Character getStatus() {
        return this.status;
    }

    public void setStatus(Character status) {
        this.status = status;
    }

    @Column(name = "create_by", length = 50)
    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "update_by", length = 50)
    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", length = 23)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bank")
    public Set<Member> getMembers() {
        return this.members;
    }

    public void setMembers(Set<Member> members) {
        this.members = members;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bank")
    public Set<BankBranch> getBankBranches() {
        return this.bankBranches;
    }

    public void setBankBranches(Set<BankBranch> bankBranches) {
        this.bankBranches = bankBranches;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bank")
    public Set<MilitaryDepartment> getMilitaryDepartments() {
        return this.militaryDepartments;
    }

    public void setMilitaryDepartments(Set<MilitaryDepartment> militaryDepartments) {
        this.militaryDepartments = militaryDepartments;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bank")
    public Set<BankAccountType> getBankAccountTypes() {
        return this.bankAccountTypes;
    }

    public void setBankAccountTypes(Set<BankAccountType> bankAccountTypes) {
        this.bankAccountTypes = bankAccountTypes;
    }

}
