package com.itos.model;
// Generated Sep 21, 2014 6:09:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ControlPayment generated by hbm2java
 */
@Entity
@Table(name="ControlPayment"
    ,schema="dbo"
    ,catalog="rtacs"
)
public class ControlPayment  implements java.io.Serializable {


     private String monthCode;
     private Date budgetMonth;
     private Integer startSopNo;
     private Integer endSopNo;
     private Long noMember;
     private BigDecimal amount;
     private String remark;
     private Date date;
     private Integer stationId;
     private String officerId;

    public ControlPayment() {
    }

	
    public ControlPayment(String monthCode) {
        this.monthCode = monthCode;
    }
    public ControlPayment(String monthCode, Date budgetMonth, Integer startSopNo, Integer endSopNo, Long noMember, BigDecimal amount, String remark, Date date, Integer stationId, String officerId) {
       this.monthCode = monthCode;
       this.budgetMonth = budgetMonth;
       this.startSopNo = startSopNo;
       this.endSopNo = endSopNo;
       this.noMember = noMember;
       this.amount = amount;
       this.remark = remark;
       this.date = date;
       this.stationId = stationId;
       this.officerId = officerId;
    }
   
     @Id 

    
    @Column(name="month_code", unique=true, nullable=false, length=50)
    public String getMonthCode() {
        return this.monthCode;
    }
    
    public void setMonthCode(String monthCode) {
        this.monthCode = monthCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="budget_month", length=23)
    public Date getBudgetMonth() {
        return this.budgetMonth;
    }
    
    public void setBudgetMonth(Date budgetMonth) {
        this.budgetMonth = budgetMonth;
    }

    
    @Column(name="start_sop_no")
    public Integer getStartSopNo() {
        return this.startSopNo;
    }
    
    public void setStartSopNo(Integer startSopNo) {
        this.startSopNo = startSopNo;
    }

    
    @Column(name="end_sop_no")
    public Integer getEndSopNo() {
        return this.endSopNo;
    }
    
    public void setEndSopNo(Integer endSopNo) {
        this.endSopNo = endSopNo;
    }

    
    @Column(name="no_member")
    public Long getNoMember() {
        return this.noMember;
    }
    
    public void setNoMember(Long noMember) {
        this.noMember = noMember;
    }

    
    @Column(name="amount", precision=10, scale=4)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="remark")
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=23)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="station_id")
    public Integer getStationId() {
        return this.stationId;
    }
    
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    
    @Column(name="officer_id", length=50)
    public String getOfficerId() {
        return this.officerId;
    }
    
    public void setOfficerId(String officerId) {
        this.officerId = officerId;
    }




}


