package com.itos.model;
// Generated Sep 21, 2014 6:09:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeptPayment generated by hbm2java
 */
@Entity
@Table(name="DeptPayment"
    ,schema="dbo"
    ,catalog="rtacs"
)
public class DeptPayment  implements java.io.Serializable {


     private int deptpaymentId;
     private Date paymentDate;
     private Integer mildeptId;
     private String monthCode;
     private Integer numMember;
     private BigDecimal totalAmount;
     private Integer numMemberIn;
     private Integer numMemberOut;
     private String remark;
     private Integer cancel;
     private Date createdDate;
     private Integer stationId;
     private Integer officerId;
     private String createdBy;

    public DeptPayment() {
    }

	
    public DeptPayment(int deptpaymentId) {
        this.deptpaymentId = deptpaymentId;
    }
    public DeptPayment(int deptpaymentId, Date paymentDate, Integer mildeptId, String monthCode, Integer numMember, BigDecimal totalAmount, Integer numMemberIn, Integer numMemberOut, String remark, Integer cancel, Date createdDate, Integer stationId, Integer officerId, String createdBy) {
       this.deptpaymentId = deptpaymentId;
       this.paymentDate = paymentDate;
       this.mildeptId = mildeptId;
       this.monthCode = monthCode;
       this.numMember = numMember;
       this.totalAmount = totalAmount;
       this.numMemberIn = numMemberIn;
       this.numMemberOut = numMemberOut;
       this.remark = remark;
       this.cancel = cancel;
       this.createdDate = createdDate;
       this.stationId = stationId;
       this.officerId = officerId;
       this.createdBy = createdBy;
    }
   
     @Id 

    
    @Column(name="deptpayment_id", unique=true, nullable=false)
    public int getDeptpaymentId() {
        return this.deptpaymentId;
    }
    
    public void setDeptpaymentId(int deptpaymentId) {
        this.deptpaymentId = deptpaymentId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="payment_date", length=23)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="mildept_id")
    public Integer getMildeptId() {
        return this.mildeptId;
    }
    
    public void setMildeptId(Integer mildeptId) {
        this.mildeptId = mildeptId;
    }

    
    @Column(name="month_code", length=5)
    public String getMonthCode() {
        return this.monthCode;
    }
    
    public void setMonthCode(String monthCode) {
        this.monthCode = monthCode;
    }

    
    @Column(name="num_member")
    public Integer getNumMember() {
        return this.numMember;
    }
    
    public void setNumMember(Integer numMember) {
        this.numMember = numMember;
    }

    
    @Column(name="total_amount", precision=10, scale=4)
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    
    @Column(name="num_member_in")
    public Integer getNumMemberIn() {
        return this.numMemberIn;
    }
    
    public void setNumMemberIn(Integer numMemberIn) {
        this.numMemberIn = numMemberIn;
    }

    
    @Column(name="num_member_out")
    public Integer getNumMemberOut() {
        return this.numMemberOut;
    }
    
    public void setNumMemberOut(Integer numMemberOut) {
        this.numMemberOut = numMemberOut;
    }

    
    @Column(name="remark")
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="cancel")
    public Integer getCancel() {
        return this.cancel;
    }
    
    public void setCancel(Integer cancel) {
        this.cancel = cancel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="station_id")
    public Integer getStationId() {
        return this.stationId;
    }
    
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    
    @Column(name="officer_id")
    public Integer getOfficerId() {
        return this.officerId;
    }
    
    public void setOfficerId(Integer officerId) {
        this.officerId = officerId;
    }

    
    @Column(name="created_by", length=50)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


