package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogsSendMail generated by hbm2java
 */
@Entity
@Table(name = "logs_send_mail", schema = "dbo", catalog = "rtacs"
)
public class LogsSendMail implements java.io.Serializable {

    private String logsSendMailId;
    private String nameFrom;
    private String fromEmail;
    private String nameTo;
    private String toEmail;
    private String subjectEmail;
    private String bodyEmail;
    private String bodyEmailSize;
    private String bodyEmailType;
    private String attachmentEmail;
    private String attachmentTypeEmail;
    private Long sizeFile;
    private String dnsServerEmail;
    private Integer portEmail;
    private String authentication;
    private String userSmtp;
    private String passwordSmtp;
    private String sendData;
    private String sendStatus;
    private Date dateTimeCreate;
    private String userCreate;

    public LogsSendMail() {
    }

    public LogsSendMail(String logsSendMailId) {
        this.logsSendMailId = logsSendMailId;
    }

    public LogsSendMail(String logsSendMailId, String nameFrom, String fromEmail, String nameTo, String toEmail, String subjectEmail, String bodyEmail, String bodyEmailSize, String bodyEmailType, String attachmentEmail, String attachmentTypeEmail, Long sizeFile, String dnsServerEmail, Integer portEmail, String authentication, String userSmtp, String passwordSmtp, String sendData, String sendStatus, Date dateTimeCreate, String userCreate) {
        this.logsSendMailId = logsSendMailId;
        this.nameFrom = nameFrom;
        this.fromEmail = fromEmail;
        this.nameTo = nameTo;
        this.toEmail = toEmail;
        this.subjectEmail = subjectEmail;
        this.bodyEmail = bodyEmail;
        this.bodyEmailSize = bodyEmailSize;
        this.bodyEmailType = bodyEmailType;
        this.attachmentEmail = attachmentEmail;
        this.attachmentTypeEmail = attachmentTypeEmail;
        this.sizeFile = sizeFile;
        this.dnsServerEmail = dnsServerEmail;
        this.portEmail = portEmail;
        this.authentication = authentication;
        this.userSmtp = userSmtp;
        this.passwordSmtp = passwordSmtp;
        this.sendData = sendData;
        this.sendStatus = sendStatus;
        this.dateTimeCreate = dateTimeCreate;
        this.userCreate = userCreate;
    }

    @Id

    @Column(name = "Logs_Send_Mail_Id", unique = true, nullable = false, length = 36)
    public String getLogsSendMailId() {
        return this.logsSendMailId;
    }

    public void setLogsSendMailId(String logsSendMailId) {
        this.logsSendMailId = logsSendMailId;
    }

    @Column(name = "Name_From", length = 250)
    public String getNameFrom() {
        return this.nameFrom;
    }

    public void setNameFrom(String nameFrom) {
        this.nameFrom = nameFrom;
    }

    @Column(name = "From_Email", length = 250)
    public String getFromEmail() {
        return this.fromEmail;
    }

    public void setFromEmail(String fromEmail) {
        this.fromEmail = fromEmail;
    }

    @Column(name = "Name_To", length = 2048)
    public String getNameTo() {
        return this.nameTo;
    }

    public void setNameTo(String nameTo) {
        this.nameTo = nameTo;
    }

    @Column(name = "To_Email", length = 2048)
    public String getToEmail() {
        return this.toEmail;
    }

    public void setToEmail(String toEmail) {
        this.toEmail = toEmail;
    }

    @Column(name = "Subject_Email", length = 2048)
    public String getSubjectEmail() {
        return this.subjectEmail;
    }

    public void setSubjectEmail(String subjectEmail) {
        this.subjectEmail = subjectEmail;
    }

    @Column(name = "Body_Email")
    public String getBodyEmail() {
        return this.bodyEmail;
    }

    public void setBodyEmail(String bodyEmail) {
        this.bodyEmail = bodyEmail;
    }

    @Column(name = "Body_Email_Size", length = 2048)
    public String getBodyEmailSize() {
        return this.bodyEmailSize;
    }

    public void setBodyEmailSize(String bodyEmailSize) {
        this.bodyEmailSize = bodyEmailSize;
    }

    @Column(name = "Body_Email_Type", length = 2048)
    public String getBodyEmailType() {
        return this.bodyEmailType;
    }

    public void setBodyEmailType(String bodyEmailType) {
        this.bodyEmailType = bodyEmailType;
    }

    @Column(name = "Attachment_Email", length = 2048)
    public String getAttachmentEmail() {
        return this.attachmentEmail;
    }

    public void setAttachmentEmail(String attachmentEmail) {
        this.attachmentEmail = attachmentEmail;
    }

    @Column(name = "Attachment_Type_Email", length = 1024)
    public String getAttachmentTypeEmail() {
        return this.attachmentTypeEmail;
    }

    public void setAttachmentTypeEmail(String attachmentTypeEmail) {
        this.attachmentTypeEmail = attachmentTypeEmail;
    }

    @Column(name = "Size_File")
    public Long getSizeFile() {
        return this.sizeFile;
    }

    public void setSizeFile(Long sizeFile) {
        this.sizeFile = sizeFile;
    }

    @Column(name = "DNS_Server_Email", length = 250)
    public String getDnsServerEmail() {
        return this.dnsServerEmail;
    }

    public void setDnsServerEmail(String dnsServerEmail) {
        this.dnsServerEmail = dnsServerEmail;
    }

    @Column(name = "Port_Email")
    public Integer getPortEmail() {
        return this.portEmail;
    }

    public void setPortEmail(Integer portEmail) {
        this.portEmail = portEmail;
    }

    @Column(name = "Authentication", length = 50)
    public String getAuthentication() {
        return this.authentication;
    }

    public void setAuthentication(String authentication) {
        this.authentication = authentication;
    }

    @Column(name = "User_SMTP", length = 2000)
    public String getUserSmtp() {
        return this.userSmtp;
    }

    public void setUserSmtp(String userSmtp) {
        this.userSmtp = userSmtp;
    }

    @Column(name = "Password_SMTP", length = 2000)
    public String getPasswordSmtp() {
        return this.passwordSmtp;
    }

    public void setPasswordSmtp(String passwordSmtp) {
        this.passwordSmtp = passwordSmtp;
    }

    @Column(name = "Send_Data")
    public String getSendData() {
        return this.sendData;
    }

    public void setSendData(String sendData) {
        this.sendData = sendData;
    }

    @Column(name = "Send_Status")
    public String getSendStatus() {
        return this.sendStatus;
    }

    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Date_Time_Create", length = 27)
    public Date getDateTimeCreate() {
        return this.dateTimeCreate;
    }

    public void setDateTimeCreate(Date dateTimeCreate) {
        this.dateTimeCreate = dateTimeCreate;
    }

    @Column(name = "User_Create", length = 512)
    public String getUserCreate() {
        return this.userCreate;
    }

    public void setUserCreate(String userCreate) {
        this.userCreate = userCreate;
    }

}
