package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogsInOut generated by hbm2java
 */
@Entity
@Table(name = "logs_in_out", schema = "dbo", catalog = "rtacs"
)
public class LogsInOut implements java.io.Serializable {

    private String logsInOutId;
    private String userProfileId;
    private String sessionLogin;
    private String ipaddressClient;
    private String statusInOut;
    private Date dateTimeCreate;

    public LogsInOut() {
    }

    public LogsInOut(String logsInOutId) {
        this.logsInOutId = logsInOutId;
    }

    public LogsInOut(String logsInOutId, String userProfileId, String sessionLogin, String ipaddressClient, String statusInOut, Date dateTimeCreate) {
        this.logsInOutId = logsInOutId;
        this.userProfileId = userProfileId;
        this.sessionLogin = sessionLogin;
        this.ipaddressClient = ipaddressClient;
        this.statusInOut = statusInOut;
        this.dateTimeCreate = dateTimeCreate;
    }

    @Id

    @Column(name = "Logs_In_Out_Id", unique = true, nullable = false, length = 36)
    public String getLogsInOutId() {
        return this.logsInOutId;
    }

    public void setLogsInOutId(String logsInOutId) {
        this.logsInOutId = logsInOutId;
    }

    @Column(name = "User_Profile_Id", length = 64)
    public String getUserProfileId() {
        return this.userProfileId;
    }

    public void setUserProfileId(String userProfileId) {
        this.userProfileId = userProfileId;
    }

    @Column(name = "Session_Login", length = 250)
    public String getSessionLogin() {
        return this.sessionLogin;
    }

    public void setSessionLogin(String sessionLogin) {
        this.sessionLogin = sessionLogin;
    }

    @Column(name = "Ipaddress_Client", length = 250)
    public String getIpaddressClient() {
        return this.ipaddressClient;
    }

    public void setIpaddressClient(String ipaddressClient) {
        this.ipaddressClient = ipaddressClient;
    }

    @Column(name = "Status_In_Out", length = 50)
    public String getStatusInOut() {
        return this.statusInOut;
    }

    public void setStatusInOut(String statusInOut) {
        this.statusInOut = statusInOut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Date_Time_Create", length = 27)
    public Date getDateTimeCreate() {
        return this.dateTimeCreate;
    }

    public void setDateTimeCreate(Date dateTimeCreate) {
        this.dateTimeCreate = dateTimeCreate;
    }

}
