package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogsEvent generated by hbm2java
 */
@Entity
@Table(name = "logs_event", schema = "dbo", catalog = "rtacs"
)
public class LogsEvent implements java.io.Serializable {

    private String logsEventId;
    private String functionLog;
    private String actionLog;
    private String actionDetail;
    private Date dateTimeCreate;
    private String userCreate;

    public LogsEvent() {
    }

    public LogsEvent(String logsEventId) {
        this.logsEventId = logsEventId;
    }

    public LogsEvent(String logsEventId, String functionLog, String actionLog, String actionDetail, Date dateTimeCreate, String userCreate) {
        this.logsEventId = logsEventId;
        this.functionLog = functionLog;
        this.actionLog = actionLog;
        this.actionDetail = actionDetail;
        this.dateTimeCreate = dateTimeCreate;
        this.userCreate = userCreate;
    }

    @Id

    @Column(name = "Logs_Event_Id", unique = true, nullable = false, length = 36)
    public String getLogsEventId() {
        return this.logsEventId;
    }

    public void setLogsEventId(String logsEventId) {
        this.logsEventId = logsEventId;
    }

    @Column(name = "Function_Log", length = 256)
    public String getFunctionLog() {
        return this.functionLog;
    }

    public void setFunctionLog(String functionLog) {
        this.functionLog = functionLog;
    }

    @Column(name = "Action_Log", length = 256)
    public String getActionLog() {
        return this.actionLog;
    }

    public void setActionLog(String actionLog) {
        this.actionLog = actionLog;
    }

    @Column(name = "Action_Detail")
    public String getActionDetail() {
        return this.actionDetail;
    }

    public void setActionDetail(String actionDetail) {
        this.actionDetail = actionDetail;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Date_Time_Create", length = 27)
    public Date getDateTimeCreate() {
        return this.dateTimeCreate;
    }

    public void setDateTimeCreate(Date dateTimeCreate) {
        this.dateTimeCreate = dateTimeCreate;
    }

    @Column(name = "User_Create", length = 512)
    public String getUserCreate() {
        return this.userCreate;
    }

    public void setUserCreate(String userCreate) {
        this.userCreate = userCreate;
    }

}
