package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogsPassword generated by hbm2java
 */
@Entity
@Table(name = "logs_password", schema = "dbo", catalog = "rtacs"
)
public class LogsPassword implements java.io.Serializable {

    private String logsPasswordId;
    private String userProfileId;
    private String userProfilePassword;
    private String userProfilePasswordEncrypt;
    private Date dateTimeCreate;
    private String userCreate;

    public LogsPassword() {
    }

    public LogsPassword(String logsPasswordId) {
        this.logsPasswordId = logsPasswordId;
    }

    public LogsPassword(String logsPasswordId, String userProfileId, String userProfilePassword, String userProfilePasswordEncrypt, Date dateTimeCreate, String userCreate) {
        this.logsPasswordId = logsPasswordId;
        this.userProfileId = userProfileId;
        this.userProfilePassword = userProfilePassword;
        this.userProfilePasswordEncrypt = userProfilePasswordEncrypt;
        this.dateTimeCreate = dateTimeCreate;
        this.userCreate = userCreate;
    }

    @Id

    @Column(name = "Logs_Password_Id", unique = true, nullable = false, length = 36)
    public String getLogsPasswordId() {
        return this.logsPasswordId;
    }

    public void setLogsPasswordId(String logsPasswordId) {
        this.logsPasswordId = logsPasswordId;
    }

    @Column(name = "User_Profile_Id", length = 64)
    public String getUserProfileId() {
        return this.userProfileId;
    }

    public void setUserProfileId(String userProfileId) {
        this.userProfileId = userProfileId;
    }

    @Column(name = "User_Profile_Password", length = 512)
    public String getUserProfilePassword() {
        return this.userProfilePassword;
    }

    public void setUserProfilePassword(String userProfilePassword) {
        this.userProfilePassword = userProfilePassword;
    }

    @Column(name = "User_Profile_Password_Encrypt", length = 512)
    public String getUserProfilePasswordEncrypt() {
        return this.userProfilePasswordEncrypt;
    }

    public void setUserProfilePasswordEncrypt(String userProfilePasswordEncrypt) {
        this.userProfilePasswordEncrypt = userProfilePasswordEncrypt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Date_Time_Create", length = 27)
    public Date getDateTimeCreate() {
        return this.dateTimeCreate;
    }

    public void setDateTimeCreate(Date dateTimeCreate) {
        this.dateTimeCreate = dateTimeCreate;
    }

    @Column(name = "User_Create", length = 512)
    public String getUserCreate() {
        return this.userCreate;
    }

    public void setUserCreate(String userCreate) {
        this.userCreate = userCreate;
    }

}
