package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogsTransaction generated by hbm2java
 */
@Entity
@Table(name = "logs_transaction", schema = "dbo", catalog = "rtacs"
)
public class LogsTransaction implements java.io.Serializable {

    private String logsTransactionId;
    private String functionLog;
    private String actionLog;
    private String transactionDetail;
    private String messageStatus;
    private Date dateTimeCreate;
    private String userCreate;

    public LogsTransaction() {
    }

    public LogsTransaction(String logsTransactionId) {
        this.logsTransactionId = logsTransactionId;
    }

    public LogsTransaction(String logsTransactionId, String functionLog, String actionLog, String transactionDetail, String messageStatus, Date dateTimeCreate, String userCreate) {
        this.logsTransactionId = logsTransactionId;
        this.functionLog = functionLog;
        this.actionLog = actionLog;
        this.transactionDetail = transactionDetail;
        this.messageStatus = messageStatus;
        this.dateTimeCreate = dateTimeCreate;
        this.userCreate = userCreate;
    }

    @Id

    @Column(name = "Logs_Transaction_Id", unique = true, nullable = false, length = 36)
    public String getLogsTransactionId() {
        return this.logsTransactionId;
    }

    public void setLogsTransactionId(String logsTransactionId) {
        this.logsTransactionId = logsTransactionId;
    }

    @Column(name = "Function_Log", length = 256)
    public String getFunctionLog() {
        return this.functionLog;
    }

    public void setFunctionLog(String functionLog) {
        this.functionLog = functionLog;
    }

    @Column(name = "Action_Log", length = 256)
    public String getActionLog() {
        return this.actionLog;
    }

    public void setActionLog(String actionLog) {
        this.actionLog = actionLog;
    }

    @Column(name = "Transaction_Detail")
    public String getTransactionDetail() {
        return this.transactionDetail;
    }

    public void setTransactionDetail(String transactionDetail) {
        this.transactionDetail = transactionDetail;
    }

    @Column(name = "Message_Status", length = 512)
    public String getMessageStatus() {
        return this.messageStatus;
    }

    public void setMessageStatus(String messageStatus) {
        this.messageStatus = messageStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Date_Time_Create", length = 27)
    public Date getDateTimeCreate() {
        return this.dateTimeCreate;
    }

    public void setDateTimeCreate(Date dateTimeCreate) {
        this.dateTimeCreate = dateTimeCreate;
    }

    @Column(name = "User_Create", length = 512)
    public String getUserCreate() {
        return this.userCreate;
    }

    public void setUserCreate(String userCreate) {
        this.userCreate = userCreate;
    }

}
