package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.hibernate.annotations.Formula;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "Member", schema = "dbo", catalog = "rtacs"
)
public class Member implements java.io.Serializable {

    private int memberId;
    private Province provinceByPermanentProvinceCode;
    private Rank rank;
    private BankAccountType bankAccountType;
    private Title title;
    private Province provinceByProvinceCode;
    private MilitaryDepartment militaryDepartment;
    private Bank bank;
    private BankBranch bankBranch;
    private Integer memberGroupCode;
    private String memberCode;
    private Date applyDate;
    private String citizenId;
    private String name;
    private String surname;
    private Character gender;
    private Date birthDate;
    private Integer memberTypeCode;
    private Integer paymentType;
    private Integer referrerId;
    private Integer referrerRelationshipCode;
    private Integer marryStatusCode;
    private String wifehusbandFullname;
    private String remark;
    private String paymentTypeCode;
    private String paymentRemark;
    private String bankAccName;
    private String bankAccNo;
    private String permanentAddress;
    private String permanentMoo;
    private String permanentRoad;
    private String permanentSoi;
    private String permanentSubdistrict;
    private String permanentDistrict;
    private String permanentZipcode;
    private String permanentTel;
    private String permanentFax;
    private String permanentMobile;
    private String address;
    private String moo;
    private String road;
    private String soi;
    private String subdistrict;
    private String district;
    private String zipcode;
    private String tel;
    private String fax;
    private String mobile;
    private Character addressPrimary;
    private Integer memberStatusCode;
    private String createBy;
    private Date createDate;
    private String updateBy;
    private Date updateDate;
    private Set<OperationMember> operationMembers = new HashSet<OperationMember>(0);
    private Set<MemberBeneficiary> memberBeneficiaries = new HashSet<MemberBeneficiary>(0);
    private Integer bankBranchId;
    private String branchCode;
    private String branchName;
    private String branchShort;
    private Integer accTypeId;
    private String accTypeName;
    private Integer militaryId;
    private String militaryName;
    private Integer rankId;
    private String rankName;
    private Integer titleId;
    private String titleName;
    private String bankCode;
    private String bankName;
    private String permanentProvinceCode;
    private String permanentProvinceName;
    private String provinceCode;
    private String provinceName;
    private String rankOrTitleName;
    private List<MemberBeneficiary> listMemberBeneficiary;
    private List<String> deleteBeneficiaryId;

    public Member() {
    }

    public Member(int memberId) {
        this.memberId = memberId;
    }

    public Member(int memberId, Province provinceByPermanentProvinceCode, Rank rank, BankAccountType bankAccountType, Title title, Province provinceByProvinceCode, MilitaryDepartment militaryDepartment, Bank bank, BankBranch bankBranch, Integer memberGroupCode, String memberCode, Date applyDate, String citizenId, String name, String surname, Character gender, Date birthDate, Integer memberTypeCode, Integer paymentType, Integer referrerId, Integer referrerRelationshipCode, Integer marryStatusCode, String wifehusbandFullname, String remark, String paymentTypeCode, String paymentRemark, String bankAccName, String bankAccNo, String permanentAddress, String permanentMoo, String permanentRoad, String permanentSoi, String permanentSubdistrict, String permanentDistrict, String permanentZipcode, String permanentTel, String permanentFax, String permanentMobile, String address, String moo, String road, String soi, String subdistrict, String district, String zipcode, String tel, String fax, String mobile, Character addressPrimary, Integer memberStatusCode, String createBy, Date createDate, String updateBy, Date updateDate, Set operationMembers, Set memberBeneficiaries) {
        this.memberId = memberId;
        this.provinceByPermanentProvinceCode = provinceByPermanentProvinceCode;
        this.rank = rank;
        this.bankAccountType = bankAccountType;
        this.title = title;
        this.provinceByProvinceCode = provinceByProvinceCode;
        this.militaryDepartment = militaryDepartment;
        this.bank = bank;
        this.bankBranch = bankBranch;
        this.memberGroupCode = memberGroupCode;
        this.memberCode = memberCode;
        this.applyDate = applyDate;
        this.citizenId = citizenId;
        this.name = name;
        this.surname = surname;
        this.gender = gender;
        this.birthDate = birthDate;
        this.memberTypeCode = memberTypeCode;
        this.paymentType = paymentType;
        this.referrerId = referrerId;
        this.referrerRelationshipCode = referrerRelationshipCode;
        this.marryStatusCode = marryStatusCode;
        this.wifehusbandFullname = wifehusbandFullname;
        this.remark = remark;
        this.paymentTypeCode = paymentTypeCode;
        this.paymentRemark = paymentRemark;
        this.bankAccName = bankAccName;
        this.bankAccNo = bankAccNo;
        this.permanentAddress = permanentAddress;
        this.permanentMoo = permanentMoo;
        this.permanentRoad = permanentRoad;
        this.permanentSoi = permanentSoi;
        this.permanentSubdistrict = permanentSubdistrict;
        this.permanentDistrict = permanentDistrict;
        this.permanentZipcode = permanentZipcode;
        this.permanentTel = permanentTel;
        this.permanentFax = permanentFax;
        this.permanentMobile = permanentMobile;
        this.address = address;
        this.moo = moo;
        this.road = road;
        this.soi = soi;
        this.subdistrict = subdistrict;
        this.district = district;
        this.zipcode = zipcode;
        this.tel = tel;
        this.fax = fax;
        this.mobile = mobile;
        this.addressPrimary = addressPrimary;
        this.memberStatusCode = memberStatusCode;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.operationMembers = operationMembers;
        this.memberBeneficiaries = memberBeneficiaries;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "member_id", unique = true, nullable = false)
    public int getMemberId() {
        return this.memberId;
    }

    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "permanent_province_code")
    @JsonBackReference
    public Province getProvinceByPermanentProvinceCode() {
        return this.provinceByPermanentProvinceCode;
    }

    public void setProvinceByPermanentProvinceCode(Province provinceByPermanentProvinceCode) {
        this.provinceByPermanentProvinceCode = provinceByPermanentProvinceCode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rank_id")
    @JsonBackReference
    public Rank getRank() {
        return this.rank;
    }

    public void setRank(Rank rank) {
        this.rank = rank;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "acc_type_id")
    @JsonBackReference
    public BankAccountType getBankAccountType() {
        return this.bankAccountType;
    }

    public void setBankAccountType(BankAccountType bankAccountType) {
        this.bankAccountType = bankAccountType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "title_id")
    @JsonBackReference
    public Title getTitle() {
        return this.title;
    }

    public void setTitle(Title title) {
        this.title = title;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "province_code")
    @JsonBackReference
    public Province getProvinceByProvinceCode() {
        return this.provinceByProvinceCode;
    }

    public void setProvinceByProvinceCode(Province provinceByProvinceCode) {
        this.provinceByProvinceCode = provinceByProvinceCode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "military_id")
    @JsonBackReference
    public MilitaryDepartment getMilitaryDepartment() {
        return this.militaryDepartment;
    }

    public void setMilitaryDepartment(MilitaryDepartment militaryDepartment) {
        this.militaryDepartment = militaryDepartment;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bank_code")
    @JsonBackReference
    public Bank getBank() {
        return this.bank;
    }

    public void setBank(Bank bank) {
        this.bank = bank;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bank_branch_id")
    @JsonBackReference
    public BankBranch getBankBranch() {
        return this.bankBranch;
    }

    public void setBankBranch(BankBranch bankBranch) {
        this.bankBranch = bankBranch;
    }

    @Column(name = "member_group_code")
    public Integer getMemberGroupCode() {
        return this.memberGroupCode;
    }

    public void setMemberGroupCode(Integer memberGroupCode) {
        this.memberGroupCode = memberGroupCode;
    }

    @Column(name = "member_code", length = 20)
    public String getMemberCode() {
        return this.memberCode;
    }

    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "apply_date", length = 23)
    public Date getApplyDate() {
        return this.applyDate;
    }

    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    @Column(name = "citizen_id", length = 13)
    public String getCitizenId() {
        return this.citizenId;
    }

    public void setCitizenId(String citizenId) {
        this.citizenId = citizenId;
    }

    @Column(name = "name", length = 256)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "surname", length = 256)
    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Column(name = "gender", length = 1)
    public Character getGender() {
        return this.gender;
    }

    public void setGender(Character gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "birth_date", length = 23)
    public Date getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    @Column(name = "member_type_code")
    public Integer getMemberTypeCode() {
        return this.memberTypeCode;
    }

    public void setMemberTypeCode(Integer memberTypeCode) {
        this.memberTypeCode = memberTypeCode;
    }

    @Column(name = "payment_type")
    public Integer getPaymentType() {
        return this.paymentType;
    }

    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    @Column(name = "referrer_id")
    public Integer getReferrerId() {
        return this.referrerId;
    }

    public void setReferrerId(Integer referrerId) {
        this.referrerId = referrerId;
    }

    @Column(name = "referrer_relationship_code")
    public Integer getReferrerRelationshipCode() {
        return this.referrerRelationshipCode;
    }

    public void setReferrerRelationshipCode(Integer referrerRelationshipCode) {
        this.referrerRelationshipCode = referrerRelationshipCode;
    }

    @Column(name = "marry_status_code")
    public Integer getMarryStatusCode() {
        return this.marryStatusCode;
    }

    public void setMarryStatusCode(Integer marryStatusCode) {
        this.marryStatusCode = marryStatusCode;
    }

    @Column(name = "wifehusband_fullname", length = 256)
    public String getWifehusbandFullname() {
        return this.wifehusbandFullname;
    }

    public void setWifehusbandFullname(String wifehusbandFullname) {
        this.wifehusbandFullname = wifehusbandFullname;
    }

    @Column(name = "remark")
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "payment_type_code", length = 10)
    public String getPaymentTypeCode() {
        return this.paymentTypeCode;
    }

    public void setPaymentTypeCode(String paymentTypeCode) {
        this.paymentTypeCode = paymentTypeCode;
    }

    @Column(name = "payment_remark")
    public String getPaymentRemark() {
        return this.paymentRemark;
    }

    public void setPaymentRemark(String paymentRemark) {
        this.paymentRemark = paymentRemark;
    }

    @Column(name = "bank_acc_name", length = 256)
    public String getBankAccName() {
        return this.bankAccName;
    }

    public void setBankAccName(String bankAccName) {
        this.bankAccName = bankAccName;
    }

    @Column(name = "bank_acc_no", length = 15)
    public String getBankAccNo() {
        return this.bankAccNo;
    }

    public void setBankAccNo(String bankAccNo) {
        this.bankAccNo = bankAccNo;
    }

    @Column(name = "permanent_address", length = 100)
    public String getPermanentAddress() {
        return this.permanentAddress;
    }

    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }

    @Column(name = "permanent_moo", length = 100)
    public String getPermanentMoo() {
        return this.permanentMoo;
    }

    public void setPermanentMoo(String permanentMoo) {
        this.permanentMoo = permanentMoo;
    }

    @Column(name = "permanent_road", length = 100)
    public String getPermanentRoad() {
        return this.permanentRoad;
    }

    public void setPermanentRoad(String permanentRoad) {
        this.permanentRoad = permanentRoad;
    }

    @Column(name = "permanent_soi", length = 100)
    public String getPermanentSoi() {
        return this.permanentSoi;
    }

    public void setPermanentSoi(String permanentSoi) {
        this.permanentSoi = permanentSoi;
    }

    @Column(name = "permanent_subdistrict", length = 100)
    public String getPermanentSubdistrict() {
        return this.permanentSubdistrict;
    }

    public void setPermanentSubdistrict(String permanentSubdistrict) {
        this.permanentSubdistrict = permanentSubdistrict;
    }

    @Column(name = "permanent_district", length = 100)
    public String getPermanentDistrict() {
        return this.permanentDistrict;
    }

    public void setPermanentDistrict(String permanentDistrict) {
        this.permanentDistrict = permanentDistrict;
    }

    @Column(name = "permanent_zipcode", length = 10)
    public String getPermanentZipcode() {
        return this.permanentZipcode;
    }

    public void setPermanentZipcode(String permanentZipcode) {
        this.permanentZipcode = permanentZipcode;
    }

    @Column(name = "permanent_tel", length = 100)
    public String getPermanentTel() {
        return this.permanentTel;
    }

    public void setPermanentTel(String permanentTel) {
        this.permanentTel = permanentTel;
    }

    @Column(name = "permanent_fax", length = 100)
    public String getPermanentFax() {
        return this.permanentFax;
    }

    public void setPermanentFax(String permanentFax) {
        this.permanentFax = permanentFax;
    }

    @Column(name = "permanent_mobile", length = 50)
    public String getPermanentMobile() {
        return this.permanentMobile;
    }

    public void setPermanentMobile(String permanentMobile) {
        this.permanentMobile = permanentMobile;
    }

    @Column(name = "address", length = 100)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "moo", length = 100)
    public String getMoo() {
        return this.moo;
    }

    public void setMoo(String moo) {
        this.moo = moo;
    }

    @Column(name = "road", length = 100)
    public String getRoad() {
        return this.road;
    }

    public void setRoad(String road) {
        this.road = road;
    }

    @Column(name = "soi", length = 100)
    public String getSoi() {
        return this.soi;
    }

    public void setSoi(String soi) {
        this.soi = soi;
    }

    @Column(name = "subdistrict", length = 100)
    public String getSubdistrict() {
        return this.subdistrict;
    }

    public void setSubdistrict(String subdistrict) {
        this.subdistrict = subdistrict;
    }

    @Column(name = "district", length = 100)
    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    @Column(name = "zipcode", length = 10)
    public String getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    @Column(name = "tel", length = 100)
    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    @Column(name = "fax", length = 100)
    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    @Column(name = "mobile", length = 50)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "address_primary", length = 1)
    public Character getAddressPrimary() {
        return this.addressPrimary;
    }

    public void setAddressPrimary(Character addressPrimary) {
        this.addressPrimary = addressPrimary;
    }

    @Column(name = "member_status_code")
    public Integer getMemberStatusCode() {
        return this.memberStatusCode;
    }

    public void setMemberStatusCode(Integer memberStatusCode) {
        this.memberStatusCode = memberStatusCode;
    }

    @Column(name = "create_by", length = 50)
    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "update_by", length = 50)
    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", length = 23)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
    @JsonManagedReference
    public Set<OperationMember> getOperationMembers() {
        return this.operationMembers;
    }

    public void setOperationMembers(Set<OperationMember> operationMembers) {
        this.operationMembers = operationMembers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
    @JsonManagedReference
    public Set<MemberBeneficiary> getMemberBeneficiaries() {
        return this.memberBeneficiaries;
    }

    public void setMemberBeneficiaries(Set<MemberBeneficiary> memberBeneficiaries) {
        this.memberBeneficiaries = memberBeneficiaries;
    }

    /**
     * @return the branchId
     */
    //@Formula("(SELECT B.branch_id FROM BankBranch B WHERE B.branch_id=bank_branch_id)")
    @Formula("(SELECT bank_branch_id)")
    public Integer getBankBranchId() {
        return bankBranchId;
    }

    /**
     * @param bankBranchId the bankBranchId to set
     */
    public void setBankBranchId(Integer bankBranchId) {
        this.bankBranchId = bankBranchId;
    }

    /**
     * @return the accTypeIid
     */
    //@Formula("(SELECT B.acc_type_id FROM BankAccountType B WHERE B.acc_type_id=acc_type_id)")
    @Formula("(SELECT acc_type_id)")
    public Integer getAccTypeId() {
        return accTypeId;
    }

    /**
     * @param accTypeId the accTypeId to set
     */
    public void setAccTypeId(Integer accTypeId) {
        this.accTypeId = accTypeId;
    }

    /**
     * @return the militaryId
     */
    //@Formula("(SELECT M.military_id FROM MilitaryDepartment M WHERE M.military_id=military_id)")
    @Formula("(SELECT military_id)")
    public Integer getMilitaryId() {
        return militaryId;
    }

    /**
     * @param militaryId the militaryId to set
     */
    public void setMilitaryId(Integer militaryId) {
        this.militaryId = militaryId;
    }

    /**
     * @return the rankId
     */
    //@Formula("(SELECT R.rank_id FROM Rank R WHERE R.rank_id=rank_id)")
    @Formula("(SELECT rank_id)")
    public Integer getRankId() {
        return rankId;
    }

    /**
     * @param rankId the rankId to set
     */
    public void setRankId(Integer rankId) {
        this.rankId = rankId;
    }

    /**
     * @return the titleId
     */
    //@Formula("(SELECT T.title_id FROM Title T WHERE T.title_id=title_id)")
    @Formula("(SELECT title_id)")
    public Integer getTitleId() {
        return titleId;
    }

    /**
     * @param titleId the titleId to set
     */
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    /**
     * @return the bankCode
     */
    //@Formula("(SELECT B.bank_code FROM Bank B WHERE B.bank_code=bank_code)")
    @Formula("(SELECT bank_code)")
    public String getBankCode() {
        return bankCode;
    }

    /**
     * @param bankCode the bankCode to set
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * @return the permanentProvinceCode
     */
    //@Formula("(SELECT P.province_code FROM Province P WHERE P.province_code=permanent_province_code)")
    @Formula("(SELECT permanent_province_code)")
    public String getPermanentProvinceCode() {
        return permanentProvinceCode;
    }

    /**
     * @param permanentProvinceCode the permanentProvinceCode to set
     */
    public void setPermanentProvinceCode(String permanentProvinceCode) {
        this.permanentProvinceCode = permanentProvinceCode;
    }

    /**
     * @return the provinceCode
     */
    //@Formula("(SELECT P.province_code FROM Province P WHERE P.province_code=province_code)")
    @Formula("(SELECT province_code)")
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * @param provinceCode the provinceCode to set
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * @return the militaryName
     */
    @Formula("(SELECT M.name FROM MilitaryDepartment M WHERE M.military_id=military_id)")
    public String getMilitaryName() {
        return militaryName;
    }

    /**
     * @param militaryName the militaryName to set
     */
    public void setMilitaryName(String militaryName) {
        this.militaryName = militaryName;
    }

    /**
     * @return the branchCode
     */
    @Formula("(SELECT B.branch_code FROM BankBranch B WHERE B.branch_id=bank_branch_id)")
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * @param branchCode the branchCode to set
     */
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    /**
     * @return the branchName
     */
    @Formula("(SELECT B.branch_name FROM BankBranch B WHERE B.branch_id=bank_branch_id)")
    public String getBranchName() {
        return branchName;
    }

    /**
     * @param branchName the branchName to set
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    /**
     * @return the branchShort
     */
    @Formula("(SELECT B.branch_short FROM BankBranch B WHERE B.branch_id=bank_branch_id)")
    public String getBranchShort() {
        return branchShort;
    }

    /**
     * @param branchShort the branchShort to set
     */
    public void setBranchShort(String branchShort) {
        this.branchShort = branchShort;
    }

    /**
     * @return the accTypeName
     */
    @Formula("(SELECT B.acc_type_name FROM BankAccountType B WHERE B.acc_type_id=acc_type_id)")
    public String getAccTypeName() {
        return accTypeName;
    }

    /**
     * @param accTypeName the accTypeName to set
     */
    public void setAccTypeName(String accTypeName) {
        this.accTypeName = accTypeName;
    }

    /**
     * @return the rankName
     */
    @Formula("(SELECT R.rank_name FROM Rank R WHERE R.rank_id=rank_id)")
    public String getRankName() {
        return rankName;
    }

    /**
     * @param rankName the rankName to set
     */
    public void setRankName(String rankName) {
        this.rankName = rankName;
    }

    /**
     * @return the titleName
     */
    @Formula("(SELECT T.title FROM Title T WHERE T.title_id=title_id)")
    public String getTitleName() {
        return titleName;
    }

    /**
     * @param titleName the titleName to set
     */
    public void setTitleName(String titleName) {
        this.titleName = titleName;
    }

    /**
     * @return the bankName
     */
    @Formula("(SELECT B.bank_name FROM Bank B WHERE B.bank_code=bank_code)")
    public String getBankName() {
        return bankName;
    }

    /**
     * @param bankName the bankName to set
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * @return the permanentProvinceName
     */
    @Formula("(SELECT P.province_name FROM Province P WHERE P.province_code=permanent_province_code)")
    public String getPermanentProvinceName() {
        return permanentProvinceName;
    }

    /**
     * @param permanentProvinceName the permanentProvinceName to set
     */
    public void setPermanentProvinceName(String permanentProvinceName) {
        this.permanentProvinceName = permanentProvinceName;
    }

    /**
     * @return the provinceName
     */
    @Formula("(SELECT P.province_name FROM Province P WHERE P.province_code=province_code)")
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * @param provinceName the provinceName to set
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * @return the rankOrTitleName
     */
    @Transient
    public String getRankOrTitleName() {
        return rankOrTitleName;
    }

    /**
     * @param rankOrTitleName the rankOrTitleName to set
     */
    public void setRankOrTitleName(String rankOrTitleName) {
        this.rankOrTitleName = rankOrTitleName;
    }

    /**
     * @return the listMemberBeneficiary
     */
    @Transient
    public List<MemberBeneficiary> getListMemberBeneficiary() {
        return listMemberBeneficiary;
    }

    /**
     * @param listMemberBeneficiary the listMemberBeneficiary to set
     */
    public void setListMemberBeneficiary(List<MemberBeneficiary> listMemberBeneficiary) {
        this.listMemberBeneficiary = listMemberBeneficiary;
    }

    /**
     * @return the deleteBeneficiaryId
     */
    @Transient
    public List<String> getDeleteBeneficiaryId() {
        return deleteBeneficiaryId;
    }

    /**
     * @param deleteBeneficiaryId the deleteBeneficiaryId to set
     */
    public void setDeleteBeneficiaryId(List<String> deleteBeneficiaryId) {
        this.deleteBeneficiaryId = deleteBeneficiaryId;
    }

}
