package com.my.test;
// Generated Sep 13, 2014 5:40:42 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberPaymentHead generated by hbm2java
 */
@Entity
@Table(name="MemberPaymentHead"
    ,schema="dbo"
    ,catalog="rtacs"
)
public class MemberPaymentHead  implements java.io.Serializable {


     private int paymentId;
     private Integer memberId;
     private Date paymentDate;
     private String receiptNo;
     private Integer paymentTypeCode;
     private BigDecimal amont;
     private Integer cancelFlag;
     private Date createdDate;
     private Integer createdBy;
     private Date updatedDate;
     private Integer updatedBy;

    public MemberPaymentHead() {
    }

	
    public MemberPaymentHead(int paymentId) {
        this.paymentId = paymentId;
    }
    public MemberPaymentHead(int paymentId, Integer memberId, Date paymentDate, String receiptNo, Integer paymentTypeCode, BigDecimal amont, Integer cancelFlag, Date createdDate, Integer createdBy, Date updatedDate, Integer updatedBy) {
       this.paymentId = paymentId;
       this.memberId = memberId;
       this.paymentDate = paymentDate;
       this.receiptNo = receiptNo;
       this.paymentTypeCode = paymentTypeCode;
       this.amont = amont;
       this.cancelFlag = cancelFlag;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.updatedDate = updatedDate;
       this.updatedBy = updatedBy;
    }
   
     @Id 

    
    @Column(name="payment_id", unique=true, nullable=false)
    public int getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }

    
    @Column(name="member_id")
    public Integer getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="payment_date", length=23)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="receipt_no", length=50)
    public String getReceiptNo() {
        return this.receiptNo;
    }
    
    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }

    
    @Column(name="payment_type_code")
    public Integer getPaymentTypeCode() {
        return this.paymentTypeCode;
    }
    
    public void setPaymentTypeCode(Integer paymentTypeCode) {
        this.paymentTypeCode = paymentTypeCode;
    }

    
    @Column(name="amont", precision=14, scale=4)
    public BigDecimal getAmont() {
        return this.amont;
    }
    
    public void setAmont(BigDecimal amont) {
        this.amont = amont;
    }

    
    @Column(name="cancel_flag")
    public Integer getCancelFlag() {
        return this.cancelFlag;
    }
    
    public void setCancelFlag(Integer cancelFlag) {
        this.cancelFlag = cancelFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="created_by")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_date", length=23)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    
    @Column(name="updated_by")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }




}


