/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.itos.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "MemberTitleNameHistory", schema = "dbo", catalog = "rtacs"
)
public class MemberTitleNameHistory implements java.io.Serializable {
    
    private int titleameHistoryId;
    private Member member;
    private Integer fileTypeCode;
    private Title title;
    private Rank rank;
    private String name;
    private String surname;
    private Integer approved;
    private Date approvedDate;
    private String approvedBy;
    private Integer aprOfficerId;
    private Integer cancel;
    private Integer stationId;
    private Integer officerId;
    private Integer aprStationId;
    private Character titleIschange;
    private Character rankIschange;
    private Character nameIschange;
    private Character surnameIschange;
    private String docName;
    private String docNo;
    private String docIssueBy;
    private Date docIssueDate;
    private String remark;
    private String createdBy;
    private Date createdDate;

    public MemberTitleNameHistory() {
    }

    public MemberTitleNameHistory(Integer titleameHistoryId) {
        this.titleameHistoryId = titleameHistoryId;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "titleame_history_id", unique = true, nullable = false)
    public int getTitleameHistoryId() {
        return titleameHistoryId;
    }

    public void setTitleameHistoryId(int titleameHistoryId) {
        this.titleameHistoryId = titleameHistoryId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id", nullable = true)
    @JsonBackReference
    public Member getMember() {
        return member;
    }

    public void setMember(Member member) {
        this.member = member;
    }

    @Column(name = "file_type_code")
    public Integer getFileTypeCode() {
        return fileTypeCode;
    }

    public void setFileTypeCode(Integer fileTypeCode) {
        this.fileTypeCode = fileTypeCode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "title_id")
    @JsonBackReference
    public Title getTitle() {
        return this.title;
    }

    public void setTitle(Title title) {
        this.title = title;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rank_id")
    @JsonBackReference
    public Rank getRank() {
        return rank;
    }

    public void setRank(Rank rank) {
        this.rank = rank;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "surname", length = 100)
    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Column(name = "approved")
    public Integer getApproved() {
        return approved;
    }

    public void setApproved(Integer approved) {
        this.approved = approved;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "approved_date", length = 23)
    public Date getApprovedDate() {
        return approvedDate;
    }

    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    @Column(name = "approved_by", length = 50)
    public String getApprovedBy() {
        return approvedBy;
    }

    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }

    @Column(name = "apr_officer_id")
    public Integer getAprOfficerId() {
        return aprOfficerId;
    }

    public void setAprOfficerId(Integer aprOfficerId) {
        this.aprOfficerId = aprOfficerId;
    }

    @Column(name = "cancel")
    public Integer getCancel() {
        return cancel;
    }

    public void setCancel(Integer cancel) {
        this.cancel = cancel;
    }

    @Column(name = "station_id")
    public Integer getStationId() {
        return stationId;
    }

    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    @Column(name = "officer_id")
    public Integer getOfficerId() {
        return officerId;
    }

    public void setOfficerId(Integer officerId) {
        this.officerId = officerId;
    }

    @Column(name = "apr_station_id")
    public Integer getAprStationId() {
        return aprStationId;
    }

    public void setAprStationId(Integer aprStationId) {
        this.aprStationId = aprStationId;
    }

    @Column(name = "title_ischange", length = 1)
    public Character getTitleIschange() {
        return titleIschange;
    }

    public void setTitleIschange(Character titleIschange) {
        this.titleIschange = titleIschange;
    }

    @Column(name = "rank_ischange", length = 1)
    public Character getRankIschange() {
        return rankIschange;
    }

    public void setRankIschange(Character rankIschange) {
        this.rankIschange = rankIschange;
    }

    @Column(name = "name_ischange", length = 1)
    public Character getNameIschange() {
        return nameIschange;
    }

    public void setNameIschange(Character nameIschange) {
        this.nameIschange = nameIschange;
    }

    @Column(name = "surname_ischange", length = 1)
    public Character getSurnameIschange() {
        return surnameIschange;
    }

    public void setSurnameIschange(Character surnameIschange) {
        this.surnameIschange = surnameIschange;
    }

    @Column(name = "doc_name", length = 256)
    public String getDocName() {
        return docName;
    }

    public void setDocName(String docName) {
        this.docName = docName;
    }

    @Column(name = "doc_no", length = 50)
    public String getDocNo() {
        return docNo;
    }

    public void setDocNo(String docNo) {
        this.docNo = docNo;
    }

    @Column(name = "doc_issue_by", length = 256)
    public String getDocIssueBy() {
        return docIssueBy;
    }

    public void setDocIssueBy(String docIssueBy) {
        this.docIssueBy = docIssueBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "doc_issue_date", length = 23)
    public Date getDocIssueDate() {
        return docIssueDate;
    }

    public void setDocIssueDate(Date docIssueDate) {
        this.docIssueDate = docIssueDate;
    }

    @Column(name = "remark")
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "created_by", length = 50)
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 23)
    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

}
