package com.itos.model;
// Generated Sep 24, 2014 5:12:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberPaymentTypeHistory generated by hbm2java
 */
@Entity
@Table(name="MemberPaymentTypeHistory"
    ,schema="dbo"
    ,catalog="rtacs"
)
public class MemberPaymentTypeHistory  implements java.io.Serializable {


     private int paymenttypeHistoryId;
     private int memberId;
     private Integer changeCode;
     private Integer paymentTypeCode;
     private String remark;
     private Integer approved;
     private Integer cancel;
     private Integer stationId;
     private Integer officerId;
     private Date approvedDate;
     private String approvedBy;
     private Date createdDate;
     private String createdBy;

    public MemberPaymentTypeHistory() {
    }

	
    public MemberPaymentTypeHistory(int paymenttypeHistoryId, int memberId) {
        this.paymenttypeHistoryId = paymenttypeHistoryId;
        this.memberId = memberId;
    }
    public MemberPaymentTypeHistory(int paymenttypeHistoryId, int memberId, Integer changeCode, Integer paymentTypeCode, String remark, Integer approved, Integer cancel, Integer stationId, Integer officerId, Date approvedDate, String approvedBy, Date createdDate, String createdBy) {
       this.paymenttypeHistoryId = paymenttypeHistoryId;
       this.memberId = memberId;
       this.changeCode = changeCode;
       this.paymentTypeCode = paymentTypeCode;
       this.remark = remark;
       this.approved = approved;
       this.cancel = cancel;
       this.stationId = stationId;
       this.officerId = officerId;
       this.approvedDate = approvedDate;
       this.approvedBy = approvedBy;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
    }
   
     @Id 

    
    @Column(name="paymenttype_history_id", unique=true, nullable=false)
    public int getPaymenttypeHistoryId() {
        return this.paymenttypeHistoryId;
    }
    
    public void setPaymenttypeHistoryId(int paymenttypeHistoryId) {
        this.paymenttypeHistoryId = paymenttypeHistoryId;
    }

    
    @Column(name="member_id", nullable=false)
    public int getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }

    
    @Column(name="change_code")
    public Integer getChangeCode() {
        return this.changeCode;
    }
    
    public void setChangeCode(Integer changeCode) {
        this.changeCode = changeCode;
    }

    
    @Column(name="payment_type_code")
    public Integer getPaymentTypeCode() {
        return this.paymentTypeCode;
    }
    
    public void setPaymentTypeCode(Integer paymentTypeCode) {
        this.paymentTypeCode = paymentTypeCode;
    }

    
    @Column(name="remark")
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="approved")
    public Integer getApproved() {
        return this.approved;
    }
    
    public void setApproved(Integer approved) {
        this.approved = approved;
    }

    
    @Column(name="cancel")
    public Integer getCancel() {
        return this.cancel;
    }
    
    public void setCancel(Integer cancel) {
        this.cancel = cancel;
    }

    
    @Column(name="station_id")
    public Integer getStationId() {
        return this.stationId;
    }
    
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    
    @Column(name="officer_id")
    public Integer getOfficerId() {
        return this.officerId;
    }
    
    public void setOfficerId(Integer officerId) {
        this.officerId = officerId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="approved_date", length=23)
    public Date getApprovedDate() {
        return this.approvedDate;
    }
    
    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    
    @Column(name="approved_by", length=50)
    public String getApprovedBy() {
        return this.approvedBy;
    }
    
    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="created_by", length=50)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


