package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.hibernate.annotations.Formula;

/**
 * MemberBeneficiary generated by hbm2java
 */
@Entity
@Table(name = "MemberBeneficiary", schema = "dbo", catalog = "rtacs"
)
public class MemberBeneficiary implements java.io.Serializable {

    private int beneficiaryId;
    private Province provinceByPermanentProvinceCode;
    private Rank rank;
    private Title title;
    private Province provinceByProvinceCode;
    private Member member;
    private String citizenId;
    private String name;
    private String surname;
    private Integer memberRelationshipCode;
    private String permanentAddress;
    private String permanentMoo;
    private String permanentRoad;
    private String permanentSoi;
    private String permanentSubdistrict;
    private String permanentDistrict;
    private String permanentZipcode;
    private String permanentTel;
    private String permanentFax;
    private String permanentMobile;
    private String address;
    private String moo;
    private String road;
    private String soi;
    private String subdistrict;
    private String district;
    private String zipcode;
    private String tel;
    private String fax;
    private String mobile;
    private Character aliveFlage;
    private Character isManager;
    private String createBy;
    private Date createDate;
    private String updateBy;
    private Date updateDate;

    private Integer rankId;
    private String rankName;
    private Integer titleId;
    private String titleName;
    private String permanentProvinceCode;
    private String permanentProvinceName;
    private String provinceCode;
    private String provinceName;
    private int memberId;
    private String memberRelationship;
    private int id;

    public MemberBeneficiary() {
    }

    public MemberBeneficiary(int beneficiaryId, Member member) {
        this.beneficiaryId = beneficiaryId;
        this.member = member;
    }

    public MemberBeneficiary(int beneficiaryId, Province provinceByPermanentProvinceCode, Rank rank, Title title, Province provinceByProvinceCode, Member member, String citizenId, String name, String surname, Integer memberRelationshipCode, String permanentAddress, String permanentMoo, String permanentRoad, String permanentSoi, String permanentSubdistrict, String permanentDistrict, String permanentZipcode, String permanentTel, String permanentFax, String permanentMobile, String address, String moo, String road, String soi, String subdistrict, String district, String zipcode, String tel, String fax, String mobile, Character aliveFlage, Character isManager, String createBy, Date createDate, String updateBy, Date updateDate) {
        this.beneficiaryId = beneficiaryId;
        this.provinceByPermanentProvinceCode = provinceByPermanentProvinceCode;
        this.rank = rank;
        this.title = title;
        this.provinceByProvinceCode = provinceByProvinceCode;
        this.member = member;
        this.citizenId = citizenId;
        this.name = name;
        this.surname = surname;
        this.memberRelationshipCode = memberRelationshipCode;
        this.permanentAddress = permanentAddress;
        this.permanentMoo = permanentMoo;
        this.permanentRoad = permanentRoad;
        this.permanentSoi = permanentSoi;
        this.permanentSubdistrict = permanentSubdistrict;
        this.permanentDistrict = permanentDistrict;
        this.permanentZipcode = permanentZipcode;
        this.permanentTel = permanentTel;
        this.permanentFax = permanentFax;
        this.permanentMobile = permanentMobile;
        this.address = address;
        this.moo = moo;
        this.road = road;
        this.soi = soi;
        this.subdistrict = subdistrict;
        this.district = district;
        this.zipcode = zipcode;
        this.tel = tel;
        this.fax = fax;
        this.mobile = mobile;
        this.aliveFlage = aliveFlage;
        this.isManager = isManager;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "beneficiary_id", unique = true, nullable = false)
    public int getBeneficiaryId() {
        return this.beneficiaryId;
    }

    public void setBeneficiaryId(int beneficiaryId) {
        this.beneficiaryId = beneficiaryId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "permanent_province_code")
    @JsonBackReference
    public Province getProvinceByPermanentProvinceCode() {
        return this.provinceByPermanentProvinceCode;
    }

    public void setProvinceByPermanentProvinceCode(Province provinceByPermanentProvinceCode) {
        this.provinceByPermanentProvinceCode = provinceByPermanentProvinceCode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rank_id")
    @JsonBackReference
    public Rank getRank() {
        return this.rank;
    }

    public void setRank(Rank rank) {
        this.rank = rank;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "title_id")
    @JsonBackReference
    public Title getTitle() {
        return this.title;
    }

    public void setTitle(Title title) {
        this.title = title;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "province_code")
    @JsonBackReference
    public Province getProvinceByProvinceCode() {
        return this.provinceByProvinceCode;
    }

    public void setProvinceByProvinceCode(Province provinceByProvinceCode) {
        this.provinceByProvinceCode = provinceByProvinceCode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id", nullable = false)
    @JsonBackReference
    public Member getMember() {
        return this.member;
    }

    public void setMember(Member member) {
        this.member = member;
    }

    @Column(name = "citizen_id", length = 13)
    public String getCitizenId() {
        return this.citizenId;
    }

    public void setCitizenId(String citizenId) {
        this.citizenId = citizenId;
    }

    @Column(name = "name", length = 256)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "surname", length = 256)
    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Column(name = "member_relationship_code")
    public Integer getMemberRelationshipCode() {
        return this.memberRelationshipCode;
    }

    public void setMemberRelationshipCode(Integer memberRelationshipCode) {
        this.memberRelationshipCode = memberRelationshipCode;
    }

    @Column(name = "permanent_address", length = 100)
    public String getPermanentAddress() {
        return this.permanentAddress;
    }

    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }

    @Column(name = "permanent_moo", length = 100)
    public String getPermanentMoo() {
        return this.permanentMoo;
    }

    public void setPermanentMoo(String permanentMoo) {
        this.permanentMoo = permanentMoo;
    }

    @Column(name = "permanent_road", length = 100)
    public String getPermanentRoad() {
        return this.permanentRoad;
    }

    public void setPermanentRoad(String permanentRoad) {
        this.permanentRoad = permanentRoad;
    }

    @Column(name = "permanent_soi", length = 100)
    public String getPermanentSoi() {
        return this.permanentSoi;
    }

    public void setPermanentSoi(String permanentSoi) {
        this.permanentSoi = permanentSoi;
    }

    @Column(name = "permanent_subdistrict", length = 100)
    public String getPermanentSubdistrict() {
        return this.permanentSubdistrict;
    }

    public void setPermanentSubdistrict(String permanentSubdistrict) {
        this.permanentSubdistrict = permanentSubdistrict;
    }

    @Column(name = "permanent_district", length = 100)
    public String getPermanentDistrict() {
        return this.permanentDistrict;
    }

    public void setPermanentDistrict(String permanentDistrict) {
        this.permanentDistrict = permanentDistrict;
    }

    @Column(name = "permanent_zipcode", length = 10)
    public String getPermanentZipcode() {
        return this.permanentZipcode;
    }

    public void setPermanentZipcode(String permanentZipcode) {
        this.permanentZipcode = permanentZipcode;
    }

    @Column(name = "permanent_tel", length = 100)
    public String getPermanentTel() {
        return this.permanentTel;
    }

    public void setPermanentTel(String permanentTel) {
        this.permanentTel = permanentTel;
    }

    @Column(name = "permanent_fax", length = 100)
    public String getPermanentFax() {
        return this.permanentFax;
    }

    public void setPermanentFax(String permanentFax) {
        this.permanentFax = permanentFax;
    }

    @Column(name = "permanent_mobile", length = 50)
    public String getPermanentMobile() {
        return this.permanentMobile;
    }

    public void setPermanentMobile(String permanentMobile) {
        this.permanentMobile = permanentMobile;
    }

    @Column(name = "address", length = 100)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "moo", length = 100)
    public String getMoo() {
        return this.moo;
    }

    public void setMoo(String moo) {
        this.moo = moo;
    }

    @Column(name = "road", length = 100)
    public String getRoad() {
        return this.road;
    }

    public void setRoad(String road) {
        this.road = road;
    }

    @Column(name = "soi", length = 100)
    public String getSoi() {
        return this.soi;
    }

    public void setSoi(String soi) {
        this.soi = soi;
    }

    @Column(name = "subdistrict", length = 100)
    public String getSubdistrict() {
        return this.subdistrict;
    }

    public void setSubdistrict(String subdistrict) {
        this.subdistrict = subdistrict;
    }

    @Column(name = "district", length = 100)
    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    @Column(name = "zipcode", length = 10)
    public String getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    @Column(name = "tel", length = 100)
    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    @Column(name = "fax", length = 100)
    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    @Column(name = "mobile", length = 50)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "alive_flage", length = 1)
    public Character getAliveFlage() {
        return this.aliveFlage;
    }

    public void setAliveFlage(Character aliveFlage) {
        this.aliveFlage = aliveFlage;
    }

    @Column(name = "is_manager", length = 1)
    public Character getIsManager() {
        return this.isManager;
    }

    public void setIsManager(Character isManager) {
        this.isManager = isManager;
    }

    @Column(name = "create_by", length = 50)
    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "update_by", length = 50)
    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", length = 23)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * @return the rankId
     */
    //@Formula("(SELECT R.rank_id FROM Rank R WHERE R.rank_id=rank_id)")
    @Formula("(SELECT rank_id)")
    public Integer getRankId() {
        return rankId;
    }

    /**
     * @param rankId the rankId to set
     */
    public void setRankId(Integer rankId) {
        this.rankId = rankId;
    }

    /**
     * @return the titleId
     */
    //@Formula("(SELECT T.title_id FROM Title T WHERE T.title_id=title_id)")
    @Formula("(SELECT title_id)")
    public Integer getTitleId() {
        return titleId;
    }

    /**
     * @param titleId the titleId to set
     */
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    /**
     * @return the permanentProvinceCode
     */
    //@Formula("(SELECT P.province_code FROM Province P WHERE P.province_code=permanent_province_code)")
    @Formula("(SELECT permanent_province_code)")
    public String getPermanentProvinceCode() {
        return permanentProvinceCode;
    }

    /**
     * @param permanentProvinceCode the permanentProvinceCode to set
     */
    public void setPermanentProvinceCode(String permanentProvinceCode) {
        this.permanentProvinceCode = permanentProvinceCode;
    }

    /**
     * @return the provinceCode
     */
    //@Formula("(SELECT P.province_code FROM Province P WHERE P.province_code=province_code)")
    @Formula("(SELECT province_code)")
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * @param provinceCode the provinceCode to set
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * @return the rankName
     */
    @Formula("(SELECT R.rank_name FROM Rank R WHERE R.rank_id=rank_id)")
    public String getRankName() {
        return rankName;
    }

    /**
     * @param rankName the rankName to set
     */
    public void setRankName(String rankName) {
        this.rankName = rankName;
    }

    /**
     * @return the titleName
     */
    @Formula("(SELECT T.title FROM Title T WHERE T.title_id=title_id)")
    public String getTitleName() {
        return titleName;
    }

    /**
     * @param titleName the titleName to set
     */
    public void setTitleName(String titleName) {
        this.titleName = titleName;
    }

    /**
     * @return the permanentProvinceName
     */
    @Formula("(SELECT P.province_name FROM Province P WHERE P.province_code=permanent_province_code)")
    public String getPermanentProvinceName() {
        return permanentProvinceName;
    }

    /**
     * @param permanentProvinceName the permanentProvinceName to set
     */
    public void setPermanentProvinceName(String permanentProvinceName) {
        this.permanentProvinceName = permanentProvinceName;
    }

    /**
     * @return the provinceName
     */
    @Formula("(SELECT P.province_name FROM Province P WHERE P.province_code=province_code)")
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * @param provinceName the provinceName to set
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * @return the memberId
     */
    @Formula("(SELECT member_Id)")
    public int getMemberId() {
        return memberId;
    }

    /**
     * @param memberId the memberId to set
     */
    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }

    /**
     * @return the memberRelationship
     */
    @Transient
    public String getMemberRelationship() {
        return memberRelationship;
    }

    /**
     * @param memberRelationship the memberRelationship to set
     */
    public void setMemberRelationship(String memberRelationship) {
        this.memberRelationship = memberRelationship;
    }

    /**
     * @return the id
     */
    @Transient
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }
}
