package com.itos.model;
// Generated Sep 24, 2014 4:56:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberDeptHistory generated by hbm2java
 */
@Entity
@Table(name="MemberDeptHistory"
    ,schema="dbo"
    ,catalog="rtacs"
)
public class MemberDeptHistory  implements java.io.Serializable {


     private int deptHistoryId;
     private int memberId;
     private Integer frMildeptId;
     private Integer mildeptId;
     private String remark;
     private Integer approved;
     private Integer cancel;
     private Integer stationId;
     private Integer officerId;
     private Integer aprStationId;
     private Integer aprOfficerId;
     private Date approvedDate;
     private String approvedBy;
     private Date createdDate;
     private String createdBy;

    public MemberDeptHistory() {
    }

	
    public MemberDeptHistory(int deptHistoryId, int memberId) {
        this.deptHistoryId = deptHistoryId;
        this.memberId = memberId;
    }
    public MemberDeptHistory(int deptHistoryId, int memberId, Integer frMildeptId, Integer mildeptId, String remark, Integer approved, Integer cancel, Integer stationId, Integer officerId, Integer aprStationId, Integer aprOfficerId, Date approvedDate, String approvedBy, Date createdDate, String createdBy) {
       this.deptHistoryId = deptHistoryId;
       this.memberId = memberId;
       this.frMildeptId = frMildeptId;
       this.mildeptId = mildeptId;
       this.remark = remark;
       this.approved = approved;
       this.cancel = cancel;
       this.stationId = stationId;
       this.officerId = officerId;
       this.aprStationId = aprStationId;
       this.aprOfficerId = aprOfficerId;
       this.approvedDate = approvedDate;
       this.approvedBy = approvedBy;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
    }
   
     @Id 

    
    @Column(name="dept_history_id", unique=true, nullable=false)
    public int getDeptHistoryId() {
        return this.deptHistoryId;
    }
    
    public void setDeptHistoryId(int deptHistoryId) {
        this.deptHistoryId = deptHistoryId;
    }

    
    @Column(name="member_id", nullable=false)
    public int getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }

    
    @Column(name="fr_mildept_id")
    public Integer getFrMildeptId() {
        return this.frMildeptId;
    }
    
    public void setFrMildeptId(Integer frMildeptId) {
        this.frMildeptId = frMildeptId;
    }

    
    @Column(name="mildept_id")
    public Integer getMildeptId() {
        return this.mildeptId;
    }
    
    public void setMildeptId(Integer mildeptId) {
        this.mildeptId = mildeptId;
    }

    
    @Column(name="remark")
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="approved")
    public Integer getApproved() {
        return this.approved;
    }
    
    public void setApproved(Integer approved) {
        this.approved = approved;
    }

    
    @Column(name="cancel")
    public Integer getCancel() {
        return this.cancel;
    }
    
    public void setCancel(Integer cancel) {
        this.cancel = cancel;
    }

    
    @Column(name="station_id")
    public Integer getStationId() {
        return this.stationId;
    }
    
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    
    @Column(name="officer_id")
    public Integer getOfficerId() {
        return this.officerId;
    }
    
    public void setOfficerId(Integer officerId) {
        this.officerId = officerId;
    }

    
    @Column(name="apr_station_id")
    public Integer getAprStationId() {
        return this.aprStationId;
    }
    
    public void setAprStationId(Integer aprStationId) {
        this.aprStationId = aprStationId;
    }

    
    @Column(name="apr_officer_id")
    public Integer getAprOfficerId() {
        return this.aprOfficerId;
    }
    
    public void setAprOfficerId(Integer aprOfficerId) {
        this.aprOfficerId = aprOfficerId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="approved_date", length=23)
    public Date getApprovedDate() {
        return this.approvedDate;
    }
    
    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    
    @Column(name="approved_by", length=50)
    public String getApprovedBy() {
        return this.approvedBy;
    }
    
    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="created_by", length=50)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


