package com.itos.model;
// Generated Sep 24, 2014 4:56:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Officer generated by hbm2java
 */
@Entity
@Table(name="Officer"
    ,schema="dbo"
    ,catalog="rtacs"
)
public class Officer  implements java.io.Serializable {


     private int officerId;
     private String username;
     private String password;
     private Integer titleId;
     private Integer rankId;
     private String name;
     private String surname;
     private Character gender;
     private Integer departmentId;
     private String position;
     private String jobdescription;
     private String address;
     private String subdistrict;
     private String district;
     private String provinceCode;
     private String zipcode;
     private String tel;
     private String fax;
     private Date lastLogon;
     private Integer authorizationLevel;
     private Date dateEmploy;
     private Date dateLeave;
     private Integer activeFlag;
     private Integer remoteBranchCode;
     private String remoteNic;
     private Integer remoteAuth;
     private Date date;
     private Integer stationId;
     private Integer adminId;

    public Officer() {
    }

	
    public Officer(int officerId) {
        this.officerId = officerId;
    }
    public Officer(int officerId, String username, String password, Integer titleId, Integer rankId, String name, String surname, Character gender, Integer departmentId, String position, String jobdescription, String address, String subdistrict, String district, String provinceCode, String zipcode, String tel, String fax, Date lastLogon, Integer authorizationLevel, Date dateEmploy, Date dateLeave, Integer activeFlag, Integer remoteBranchCode, String remoteNic, Integer remoteAuth, Date date, Integer stationId, Integer adminId) {
       this.officerId = officerId;
       this.username = username;
       this.password = password;
       this.titleId = titleId;
       this.rankId = rankId;
       this.name = name;
       this.surname = surname;
       this.gender = gender;
       this.departmentId = departmentId;
       this.position = position;
       this.jobdescription = jobdescription;
       this.address = address;
       this.subdistrict = subdistrict;
       this.district = district;
       this.provinceCode = provinceCode;
       this.zipcode = zipcode;
       this.tel = tel;
       this.fax = fax;
       this.lastLogon = lastLogon;
       this.authorizationLevel = authorizationLevel;
       this.dateEmploy = dateEmploy;
       this.dateLeave = dateLeave;
       this.activeFlag = activeFlag;
       this.remoteBranchCode = remoteBranchCode;
       this.remoteNic = remoteNic;
       this.remoteAuth = remoteAuth;
       this.date = date;
       this.stationId = stationId;
       this.adminId = adminId;
    }
   
     @Id 

    
    @Column(name="officer_id", unique=true, nullable=false)
    public int getOfficerId() {
        return this.officerId;
    }
    
    public void setOfficerId(int officerId) {
        this.officerId = officerId;
    }

    
    @Column(name="username", length=15)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=15)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="title_id")
    public Integer getTitleId() {
        return this.titleId;
    }
    
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    
    @Column(name="rank_id")
    public Integer getRankId() {
        return this.rankId;
    }
    
    public void setRankId(Integer rankId) {
        this.rankId = rankId;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="surname", length=100)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="gender", length=1)
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }

    
    @Column(name="department_id")
    public Integer getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    
    @Column(name="position", length=100)
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    
    @Column(name="jobdescription")
    public String getJobdescription() {
        return this.jobdescription;
    }
    
    public void setJobdescription(String jobdescription) {
        this.jobdescription = jobdescription;
    }

    
    @Column(name="address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="subdistrict", length=100)
    public String getSubdistrict() {
        return this.subdistrict;
    }
    
    public void setSubdistrict(String subdistrict) {
        this.subdistrict = subdistrict;
    }

    
    @Column(name="district", length=100)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="province_code", length=2)
    public String getProvinceCode() {
        return this.provinceCode;
    }
    
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    
    @Column(name="zipcode", length=10)
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    
    @Column(name="tel", length=100)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    
    @Column(name="fax", length=100)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_logon", length=23)
    public Date getLastLogon() {
        return this.lastLogon;
    }
    
    public void setLastLogon(Date lastLogon) {
        this.lastLogon = lastLogon;
    }

    
    @Column(name="authorization_level")
    public Integer getAuthorizationLevel() {
        return this.authorizationLevel;
    }
    
    public void setAuthorizationLevel(Integer authorizationLevel) {
        this.authorizationLevel = authorizationLevel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_employ", length=23)
    public Date getDateEmploy() {
        return this.dateEmploy;
    }
    
    public void setDateEmploy(Date dateEmploy) {
        this.dateEmploy = dateEmploy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_leave", length=23)
    public Date getDateLeave() {
        return this.dateLeave;
    }
    
    public void setDateLeave(Date dateLeave) {
        this.dateLeave = dateLeave;
    }

    
    @Column(name="active_flag")
    public Integer getActiveFlag() {
        return this.activeFlag;
    }
    
    public void setActiveFlag(Integer activeFlag) {
        this.activeFlag = activeFlag;
    }

    
    @Column(name="RemoteBranchCode")
    public Integer getRemoteBranchCode() {
        return this.remoteBranchCode;
    }
    
    public void setRemoteBranchCode(Integer remoteBranchCode) {
        this.remoteBranchCode = remoteBranchCode;
    }

    
    @Column(name="RemoteNIC", length=38)
    public String getRemoteNic() {
        return this.remoteNic;
    }
    
    public void setRemoteNic(String remoteNic) {
        this.remoteNic = remoteNic;
    }

    
    @Column(name="remote_auth")
    public Integer getRemoteAuth() {
        return this.remoteAuth;
    }
    
    public void setRemoteAuth(Integer remoteAuth) {
        this.remoteAuth = remoteAuth;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=23)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="station_id")
    public Integer getStationId() {
        return this.stationId;
    }
    
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    
    @Column(name="admin_id")
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }




}


