package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import com.fasterxml.jackson.annotation.JsonBackReference;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import org.hibernate.annotations.Formula;

/**
 * OperationMember generated by hbm2java
 */
@Entity
@Table(name = "OperationMember", schema = "dbo", catalog = "rtacs"
)
public class OperationMember implements java.io.Serializable {

    private int operationMemberId;
    private Operation operation;
    private Member member;
    // Operation
    private Integer operationId;    
    private Integer operationTypeCode;
    private String docCode;
    private Date docDate;
    private Date createDate;
    private String remark;
    private BigDecimal amount;

    //Member
    private Integer memberId;
    private String memberCode;
    private Integer militaryId;
    private String militaryName;
    private String citizenId;
    private Integer rankId;
    private String rankName;
    private String name;
    private String surname;
    private Integer memberTypeCode;
    private Integer titleId;
    private String titleName;
    private Date applyDate;
    private Integer memberStatusCode;
    
    private List<Integer> itemSelect;
    private List<Integer> itemSelect2;

    public OperationMember() {
    }

    public OperationMember(int operationMemberId, Operation operation, Member member) {
        this.operationMemberId = operationMemberId;
        this.operation = operation;
        this.member = member;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "operation_member_id", unique = true, nullable = false)
    public int getOperationMemberId() {
        return this.operationMemberId;
    }

    public void setOperationMemberId(int operationMemberId) {
        this.operationMemberId = operationMemberId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "operation_id", nullable = true)
    @JsonBackReference
    public Operation getOperation() {
        return this.operation;
    }

    public void setOperation(Operation operation) {
        this.operation = operation;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id", nullable = true)
    @JsonBackReference
    public Member getMember() {
        return this.member;
    }

    public void setMember(Member member) {
        this.member = member;
    }
    
    /**
     * @return the memberId
     */
    @Formula("(SELECT member_id)")
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * @param memberId the memberId to set
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * @return the operationId
     */
    @Formula("(SELECT operation_id)")
    public Integer getOperationId() {
        return operationId;
    }

    /**
     * @param operationId the operationId to set
     */
    public void setOperationId(Integer operationId) {
        this.operationId = operationId;
    }     

    /**
     * @return the operationTypeCode
     */
    @Formula("(SELECT O.operation_type_code FROM Operation O WHERE O.operation_id=operation_id)")
    public Integer getOperationTypeCode() {
        return operationTypeCode;
    }

    /**
     * @param operationTypeCode the operationTypeCode to set
     */
    public void setOperationTypeCode(Integer operationTypeCode) {
        this.operationTypeCode = operationTypeCode;
    }

    /**
     * @return the docCode
     */
    @Formula("(SELECT O.doc_code FROM Operation O WHERE O.operation_id=operation_id)")
    public String getDocCode() {
        return docCode;
    }

    /**
     * @param docCode the docCode to set
     */
    public void setDocCode(String docCode) {
        this.docCode = docCode;
    }

    /**
     * @return the docDate
     */
    @Formula("(SELECT O.doc_date FROM Operation O WHERE O.operation_id=operation_id)")
    @Temporal(javax.persistence.TemporalType.DATE)
    public Date getDocDate() {
        return docDate;
    }

    /**
     * @param docDate the docDate to set
     */
    public void setDocDate(Date docDate) {
        this.docDate = docDate;
    }

    /**
     * @return the createDate
     */
    @Formula("(SELECT O.create_date FROM Operation O WHERE O.operation_id=operation_id)")
    @Temporal(javax.persistence.TemporalType.DATE)
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * @param createDate the approvalDate to set
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * @return the remark
     */
    @Formula("(SELECT O.remark FROM Operation O WHERE O.operation_id=operation_id)")
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the rankId
     */
    @Formula("(SELECT M.rank_id FROM Member M WHERE M.member_id=member_id)")
    public Integer getRankId() {
        return rankId;
    }

    /**
     * @param rankId the rankId to set
     */
    public void setRankId(Integer rankId) {
        this.rankId = rankId;
    }

    /**
     * @return the rankName
     */
    @Formula("(SELECT R.rank_name FROM Rank R inner join Member M on R.rank_id = M.rank_id where M.member_id = member_id)")
    public String getRankName() {
        return rankName;
    }

    /**
     * @param rankName the rankName to set
     */
    public void setRankName(String rankName) {
        this.rankName = rankName;
    }

    /**
     * @return the titleId
     */
    @Formula("(SELECT M.title_id FROM Member M WHERE M.member_id=member_id)")
    public Integer getTitleId() {
        return titleId;
    }

    /**
     * @param titleId the titleId to set
     */
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    /**
     * @return the titleName
     */
    @Formula("(SELECT T.title FROM Title T inner join Member M on T.title_id = M.title_id where M.member_id = member_id)")
    public String getTitleName() {
        return titleName;
    }

    /**
     * @param titleName the titleName to set
     */
    public void setTitleName(String titleName) {
        this.titleName = titleName;
    }

    /**
     * @return the memberCode
     */
    @Formula("(SELECT M.member_code FROM Member M WHERE M.member_id=member_id)")
    public String getMemberCode() {
        return memberCode;
    }

    /**
     * @param memberCode the memberCode to set
     */
    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode;
    }

    /**
     * @return the militaryId
     */
    @Formula("(SELECT M.military_id FROM Member M WHERE M.member_id=member_id)")
    public Integer getMilitaryId() {
        return militaryId;
    }

    /**
     * @param militaryId the militaryId to set
     */
    public void setMilitaryId(Integer militaryId) {
        this.militaryId = militaryId;
    }

    /**
     * @return the militaryName
     */
    @Formula("(SELECT MD.name FROM MilitaryDepartment MD inner join Member M on MD.military_id = M.military_id where M.member_id = member_id)")
    public String getMilitaryName() {
        return militaryName;
    }

    /**
     * @param militaryName the militaryName to set
     */
    public void setMilitaryName(String militaryName) {
        this.militaryName = militaryName;
    }

    /**
     * @return the citizenId
     */
    @Formula("(SELECT M.citizen_id FROM Member M WHERE M.member_id=member_id)")
    public String getCitizenId() {
        return citizenId;
    }

    /**
     * @param citizenId the citizenId to set
     */
    public void setCitizenId(String citizenId) {
        this.citizenId = citizenId;
    }

    /**
     * @return the name
     */
    @Formula("(SELECT M.name FROM Member M WHERE M.member_id=member_id)")
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the surname
     */
    @Formula("(SELECT M.surname FROM Member M WHERE M.member_id=member_id)")
    public String getSurname() {
        return surname;
    }

    /**
     * @param surname the surname to set
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * @return the memberTypeCode
     */
    @Formula("(SELECT M.member_type_code FROM Member M WHERE M.member_id=member_id)")
    public Integer getMemberTypeCode() {
        return memberTypeCode;
    }

    /**
     * @param memberTypeCode the memberTypeCode to set
     */
    public void setMemberTypeCode(Integer memberTypeCode) {
        this.memberTypeCode = memberTypeCode;
    }

    /**
     * @return the applyDate
     */
    @Formula("(SELECT M.apply_date FROM Member M WHERE M.member_id=member_id)")
    @Temporal(javax.persistence.TemporalType.DATE)
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * @param applyDate the applyDate to set
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }
    
    @Formula("(SELECT O.amount FROM Operation O WHERE O.operation_id=operation_id)")
    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    
    /**
     * @return the itemSelect
     */
    @Transient 
    public List<Integer> getItemSelect() {
        return itemSelect;
    }

    /**
     * @param itemSelect the itemSelect to set
     */
    public void setItemSelect(List<Integer> itemSelect) {
        this.itemSelect = itemSelect;
    }

    /**
     * @return the itemSelect2
     */
    @Transient
    public List<Integer> getItemSelect2() {
        return itemSelect2;
    }

    /**
     * @param itemSelect2 the itemSelect2 to set
     */
    public void setItemSelect2(List<Integer> itemSelect2) {
        this.itemSelect2 = itemSelect2;
    }

    /**
     * @return the memberStatusCode
     */
    @Formula("(SELECT M.member_status_code FROM Member M WHERE M.member_id=member_id)")
    public Integer getMemberStatusCode() {
        return memberStatusCode;
    }

    /**
     * @param memberStatusCode the memberStatusCode to set
     */
    public void setMemberStatusCode(Integer memberStatusCode) {
        this.memberStatusCode = memberStatusCode;
    }

}
