package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name = "Province", schema = "dbo", catalog = "rtacs"
)
public class Province implements java.io.Serializable {

    private String provinceCode;
    private String provinceName;
    private char status;
    private String createBy;
    private Date createDate;
    private String updateBy;
    private Date updateDate;
    private Set<BankBranch> bankBranches = new HashSet<BankBranch>(0);
    private Set<MemberBeneficiary> memberBeneficiariesForProvinceCode = new HashSet<MemberBeneficiary>(0);
    private Set<Member> membersForPermanentProvinceCode = new HashSet<Member>(0);
    private Set<MemberBeneficiary> memberBeneficiariesForPermanentProvinceCode = new HashSet<MemberBeneficiary>(0);
    private Set<Member> membersForProvinceCode = new HashSet<Member>(0);

    public Province() {
    }

    public Province(String provinceCode, String provinceName, char status) {
        this.provinceCode = provinceCode;
        this.provinceName = provinceName;
        this.status = status;
    }

    public Province(String provinceCode, String provinceName, char status, String createBy, Date createDate, String updateBy, Date updateDate, Set bankBranches, Set memberBeneficiariesForProvinceCode, Set membersForPermanentProvinceCode, Set memberBeneficiariesForPermanentProvinceCode, Set membersForProvinceCode) {
        this.provinceCode = provinceCode;
        this.provinceName = provinceName;
        this.status = status;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.bankBranches = bankBranches;
        this.memberBeneficiariesForProvinceCode = memberBeneficiariesForProvinceCode;
        this.membersForPermanentProvinceCode = membersForPermanentProvinceCode;
        this.memberBeneficiariesForPermanentProvinceCode = memberBeneficiariesForPermanentProvinceCode;
        this.membersForProvinceCode = membersForProvinceCode;
    }

    @Id

    @Column(name = "province_code", unique = true, nullable = false, length = 2)
    public String getProvinceCode() {
        return this.provinceCode;
    }

    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    @Column(name = "province_name", nullable = false, length = 100)
    public String getProvinceName() {
        return this.provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    @Column(name = "status", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "create_by", length = 50)
    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "update_by", length = 50)
    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", length = 23)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "province")
    public Set<BankBranch> getBankBranches() {
        return this.bankBranches;
    }

    public void setBankBranches(Set<BankBranch> bankBranches) {
        this.bankBranches = bankBranches;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "provinceByProvinceCode")
    public Set<MemberBeneficiary> getMemberBeneficiariesForProvinceCode() {
        return this.memberBeneficiariesForProvinceCode;
    }

    public void setMemberBeneficiariesForProvinceCode(Set<MemberBeneficiary> memberBeneficiariesForProvinceCode) {
        this.memberBeneficiariesForProvinceCode = memberBeneficiariesForProvinceCode;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "provinceByPermanentProvinceCode")
    public Set<Member> getMembersForPermanentProvinceCode() {
        return this.membersForPermanentProvinceCode;
    }

    public void setMembersForPermanentProvinceCode(Set<Member> membersForPermanentProvinceCode) {
        this.membersForPermanentProvinceCode = membersForPermanentProvinceCode;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "provinceByPermanentProvinceCode")
    public Set<MemberBeneficiary> getMemberBeneficiariesForPermanentProvinceCode() {
        return this.memberBeneficiariesForPermanentProvinceCode;
    }

    public void setMemberBeneficiariesForPermanentProvinceCode(Set<MemberBeneficiary> memberBeneficiariesForPermanentProvinceCode) {
        this.memberBeneficiariesForPermanentProvinceCode = memberBeneficiariesForPermanentProvinceCode;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "provinceByProvinceCode")
    public Set<Member> getMembersForProvinceCode() {
        return this.membersForProvinceCode;
    }

    public void setMembersForProvinceCode(Set<Member> membersForProvinceCode) {
        this.membersForProvinceCode = membersForProvinceCode;
    }

}
