package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rank generated by hbm2java
 */
@Entity
@Table(name = "Rank", schema = "dbo", catalog = "rtacs"
)
public class Rank implements java.io.Serializable {

    private int rankId;
    private String rankName;
    private Integer rankClassCode;
    private String rankFullname;
    private Integer rankOrder;
    private char status;
    private String createBy;
    private Date createDate;
    private String updateBy;
    private Date updateDate;
    private Set<Member> members = new HashSet<Member>(0);
    private Set<MemberBeneficiary> memberBeneficiaries = new HashSet<MemberBeneficiary>(0);

    public Rank() {
    }

    public Rank(int rankId, char status) {
        this.rankId = rankId;
        this.status = status;
    }

    public Rank(int rankId, String rankName, Integer rankClassCode, String rankFullname, Integer rankOrder, char status, String createBy, Date createDate, String updateBy, Date updateDate, Set members, Set memberBeneficiaries) {
        this.rankId = rankId;
        this.rankName = rankName;
        this.rankClassCode = rankClassCode;
        this.rankFullname = rankFullname;
        this.rankOrder = rankOrder;
        this.status = status;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.members = members;
        this.memberBeneficiaries = memberBeneficiaries;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "rank_id", unique = true, nullable = false)
    public int getRankId() {
        return this.rankId;
    }

    public void setRankId(int rankId) {
        this.rankId = rankId;
    }

    @Column(name = "rank_name", length = 50)
    public String getRankName() {
        return this.rankName;
    }

    public void setRankName(String rankName) {
        this.rankName = rankName;
    }

    @Column(name = "rank_class_code")
    public Integer getRankClassCode() {
        return this.rankClassCode;
    }

    public void setRankClassCode(Integer rankClassCode) {
        this.rankClassCode = rankClassCode;
    }

    @Column(name = "rank_fullname", length = 100)
    public String getRankFullname() {
        return this.rankFullname;
    }

    public void setRankFullname(String rankFullname) {
        this.rankFullname = rankFullname;
    }

    @Column(name = "rank_order")
    public Integer getRankOrder() {
        return this.rankOrder;
    }

    public void setRankOrder(Integer rankOrder) {
        this.rankOrder = rankOrder;
    }

    @Column(name = "status", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "create_by", length = 50)
    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "update_by", length = 50)
    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", length = 23)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rank")
    public Set<Member> getMembers() {
        return this.members;
    }

    public void setMembers(Set<Member> members) {
        this.members = members;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rank")
    public Set<MemberBeneficiary> getMemberBeneficiaries() {
        return this.memberBeneficiaries;
    }

    public void setMemberBeneficiaries(Set<MemberBeneficiary> memberBeneficiaries) {
        this.memberBeneficiaries = memberBeneficiaries;
    }

}
