package com.itos.model;
// Generated Sep 21, 2014 6:09:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Receipt generated by hbm2java
 */
@Entity
@Table(name="Receipt"
    ,schema="dbo"
    ,catalog="rtacs"
)
public class Receipt  implements java.io.Serializable {


     private int receiptId;
     private String receiptNo;
     private Date receiptDate;
     private Integer terminalNo;
     private Integer payerCode;
     private Integer memberId;
     private Integer mildeptId;
     private Integer payForCode;
     private BigDecimal amount;
     private Integer paymentTypeCode;
     private String moNumber;
     private String chqBankCode;
     private String chqBranchCode;
     private String chqNo;
     private String monthCode;
     private String remark;
     private Integer cancelFlag;
     private Integer stationId;
     private Integer officerId;
     private Integer cancelOfficerId;
     private String createdBy;

    public Receipt() {
    }

	
    public Receipt(int receiptId) {
        this.receiptId = receiptId;
    }
    public Receipt(int receiptId, String receiptNo, Date receiptDate, Integer terminalNo, Integer payerCode, Integer memberId, Integer mildeptId, Integer payForCode, BigDecimal amount, Integer paymentTypeCode, String moNumber, String chqBankCode, String chqBranchCode, String chqNo, String monthCode, String remark, Integer cancelFlag, Integer stationId, Integer officerId, Integer cancelOfficerId, String createdBy) {
       this.receiptId = receiptId;
       this.receiptNo = receiptNo;
       this.receiptDate = receiptDate;
       this.terminalNo = terminalNo;
       this.payerCode = payerCode;
       this.memberId = memberId;
       this.mildeptId = mildeptId;
       this.payForCode = payForCode;
       this.amount = amount;
       this.paymentTypeCode = paymentTypeCode;
       this.moNumber = moNumber;
       this.chqBankCode = chqBankCode;
       this.chqBranchCode = chqBranchCode;
       this.chqNo = chqNo;
       this.monthCode = monthCode;
       this.remark = remark;
       this.cancelFlag = cancelFlag;
       this.stationId = stationId;
       this.officerId = officerId;
       this.cancelOfficerId = cancelOfficerId;
       this.createdBy = createdBy;
    }
   
     @Id 

    
    @Column(name="receipt_id", unique=true, nullable=false)
    public int getReceiptId() {
        return this.receiptId;
    }
    
    public void setReceiptId(int receiptId) {
        this.receiptId = receiptId;
    }

    
    @Column(name="receipt_no", length=10)
    public String getReceiptNo() {
        return this.receiptNo;
    }
    
    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="receipt_date", length=23)
    public Date getReceiptDate() {
        return this.receiptDate;
    }
    
    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    
    @Column(name="terminal_no")
    public Integer getTerminalNo() {
        return this.terminalNo;
    }
    
    public void setTerminalNo(Integer terminalNo) {
        this.terminalNo = terminalNo;
    }

    
    @Column(name="payer_code")
    public Integer getPayerCode() {
        return this.payerCode;
    }
    
    public void setPayerCode(Integer payerCode) {
        this.payerCode = payerCode;
    }

    
    @Column(name="member_id")
    public Integer getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    
    @Column(name="mildept_id")
    public Integer getMildeptId() {
        return this.mildeptId;
    }
    
    public void setMildeptId(Integer mildeptId) {
        this.mildeptId = mildeptId;
    }

    
    @Column(name="pay_for_code")
    public Integer getPayForCode() {
        return this.payForCode;
    }
    
    public void setPayForCode(Integer payForCode) {
        this.payForCode = payForCode;
    }

    
    @Column(name="amount", precision=10, scale=4)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="payment_type_code")
    public Integer getPaymentTypeCode() {
        return this.paymentTypeCode;
    }
    
    public void setPaymentTypeCode(Integer paymentTypeCode) {
        this.paymentTypeCode = paymentTypeCode;
    }

    
    @Column(name="mo_number", length=15)
    public String getMoNumber() {
        return this.moNumber;
    }
    
    public void setMoNumber(String moNumber) {
        this.moNumber = moNumber;
    }

    
    @Column(name="chq_bank_code", length=5)
    public String getChqBankCode() {
        return this.chqBankCode;
    }
    
    public void setChqBankCode(String chqBankCode) {
        this.chqBankCode = chqBankCode;
    }

    
    @Column(name="chq_branch_code", length=5)
    public String getChqBranchCode() {
        return this.chqBranchCode;
    }
    
    public void setChqBranchCode(String chqBranchCode) {
        this.chqBranchCode = chqBranchCode;
    }

    
    @Column(name="chq_no", length=15)
    public String getChqNo() {
        return this.chqNo;
    }
    
    public void setChqNo(String chqNo) {
        this.chqNo = chqNo;
    }

    
    @Column(name="month_code", length=5)
    public String getMonthCode() {
        return this.monthCode;
    }
    
    public void setMonthCode(String monthCode) {
        this.monthCode = monthCode;
    }

    
    @Column(name="remark")
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="cancel_flag")
    public Integer getCancelFlag() {
        return this.cancelFlag;
    }
    
    public void setCancelFlag(Integer cancelFlag) {
        this.cancelFlag = cancelFlag;
    }

    
    @Column(name="station_id")
    public Integer getStationId() {
        return this.stationId;
    }
    
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    
    @Column(name="officer_id")
    public Integer getOfficerId() {
        return this.officerId;
    }
    
    public void setOfficerId(Integer officerId) {
        this.officerId = officerId;
    }

    
    @Column(name="cancel_officer_id")
    public Integer getCancelOfficerId() {
        return this.cancelOfficerId;
    }
    
    public void setCancelOfficerId(Integer cancelOfficerId) {
        this.cancelOfficerId = cancelOfficerId;
    }

    
    @Column(name="created_by", length=50)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


