package com.itos.model;
// Generated Aug 27, 2014 11:11:07 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Title generated by hbm2java
 */
@Entity
@Table(name = "Title", schema = "dbo", catalog = "rtacs"
)
public class Title implements java.io.Serializable {

    private int titleId;
    private String titleDesc;
    private String title;
    private char status;
    private String createBy;
    private Date createDate;
    private String updateBy;
    private Date updateDate;
    private Set<MemberBeneficiary> memberBeneficiaries = new HashSet<MemberBeneficiary>(0);
    private Set<Member> members = new HashSet<Member>(0);

    public Title() {
    }

    public Title(int titleId, char status) {
        this.titleId = titleId;
        this.status = status;
    }

    public Title(int titleId, String titleDesc, String title, char status, String createBy, Date createDate, String updateBy, Date updateDate, Set memberBeneficiaries, Set members) {
        this.titleId = titleId;
        this.titleDesc = titleDesc;
        this.title = title;
        this.status = status;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.memberBeneficiaries = memberBeneficiaries;
        this.members = members;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "title_id", unique = true, nullable = false)
    public int getTitleId() {
        return this.titleId;
    }

    public void setTitleId(int titleId) {
        this.titleId = titleId;
    }

    @Column(name = "title_desc", length = 100)
    public String getTitleDesc() {
        return this.titleDesc;
    }

    public void setTitleDesc(String titleDesc) {
        this.titleDesc = titleDesc;
    }

    @Column(name = "title", length = 100)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "status", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "create_by", length = 50)
    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "update_by", length = 50)
    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", length = 23)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "title")
    public Set<MemberBeneficiary> getMemberBeneficiaries() {
        return this.memberBeneficiaries;
    }

    public void setMemberBeneficiaries(Set<MemberBeneficiary> memberBeneficiaries) {
        this.memberBeneficiaries = memberBeneficiaries;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "title")
    public Set<Member> getMembers() {
        return this.members;
    }

    public void setMembers(Set<Member> members) {
        this.members = members;
    }

}
